### ISSUE TITLE
How is gifski licensed?

### ISSUE THREAD

**Issue by phw** [ImageOptim/gifski#1]
The web page mentions gifski is open source, but I found no information on the license used in the repository.

**Comment by pornel** [comment]
It's AGPL 3 or later, but I'm happy to give exceptions if that license doesn't suit you.

**Comment by DanScharon** [comment]
found it in `Cargo.toml`: 
> license = "AGPL-3.0+"

**Comment by phw** [comment]
Thanks, didn't check the Cargo.toml. I would suggest adding a license file to the repository, it's not quite clear you have to look into the build files. At least it will prevent further questions like this one :)

> It's AGPL 3 or later, but I'm happy to give exceptions if that license doesn't suit you.

Good to know, but works for me

**Comment by pornel** [comment]
Fixed in 916d3c44873463dd739c7b59b2b566bd12b7781e
