### ISSUE TITLE
Document library API

### ISSUE THREAD

**Issue by jeroen** [ImageOptim/gifski#10]
The webpage says:

   > ...but it can also be compiled as library for seamelss use in other apps..

I'm interested in compiling it as a library and calling from C, which API should I be using?

**Comment by pornel** [comment]
OK, I've quickly added a C API:

https://github.com/ImageOptim/gifski/blob/master/gifski.h

https://docs.rs/gifski

**Comment by jeroen** [comment]
Thanks! Is it also possible to write the gif to a buffer instead of disk?

**Comment by pornel** [comment]
It is in the Rust API where `&mut Vec` can work as a destination. I didn't expose that in C, because growable buffers there are a bit fiddly. But it could be added.

**Comment by jeroen** [comment]
OK. One more newbie question: is it possbile to include the static library and c headers with the cargo binary?

**Comment by jeroen** [comment]
Sorry that's not what I meant. When I do `cargo install gifski` I only get the `gifski` executable, I'm not seeing any libraries. Where do they get installed?

**Comment by pornel** [comment]
They don't. `cargo build` builds the libraries.

**Comment by jeroen** [comment]
Ah okay, so cargo only ships binaries, not libraries? Sorry I'm really new to rust and cargo.

**Comment by pornel** [comment]
Cargo mainly builds from source. `cargo install` is a shortcut for `git clone + cargo build + copy to /bin`. For other operations you need to do these steps manually.

**Comment by jeroen** [comment]
Ahhh okay. So what would be a script that I can give to a user to build `libgifski.a` ?

**Comment by pornel** [comment]
```sh
git clone https://github.com/ImageOptim/gifski
cd gifski
cargo build --release
# it's in ./target/release/libgifski.a 
```

**Comment by jeroen** [comment]
So does the `crates` version automatically sync with your master branch or so? Or is a crates release nothing more than a pointer to a github tag?

**Comment by pornel** [comment]
crates.io is used by Rust libraries. I keep it mostly in sync with git tags.
