### ISSUE TITLE
Option to crop

### ISSUE THREAD

**Issue by JayXon** [ImageOptim/gifski#103]
Cropping could be useful to reduce gif size, I know that I can achieve this using `ffmpeg` first, but it's more convenient if `gifski` can support this, similar to the resize options.

**Comment by kornelski** [comment]
Adding ffmpeg-like features is a never-ending task. I'd rather keep it just a basic gif encoder.

**Comment by sindresorhus** [comment]
I agree this is outside the scope of gifski.
