### ISSUE TITLE
[FeatureRequest] Add support for BGRA and BGR in gifski_add_frame_*

### ISSUE THREAD

**Issue by NickeManarin** [ImageOptim/gifski#104]
I'm working mainly with BGRA pixel format, so it would be cool if I could just send the byte array as it is instead of having to convert to RGB.

This is a feature request.

**Comment by kornelski** [comment]
Internally everything runs on RGBA only, so all `gifski_add_frame_` functions already copy and convert all other formats to RGBA. I suggest just converting before calling `gifski_add_frame_rgba`.

**Comment by NickeManarin** [comment]
Ah, alright. I'll keep doing that. Thanks.
