### ISSUE TITLE
Gifski can't recognize unchanged pixels

### ISSUE THREAD

**Issue by byzod** [ImageOptim/gifski#105]
Cross post from project [ScreenToGif issue 556](https://github.com/NickeManarin/ScreenToGif/issues/556)

---

Screen To Gif: 2.19.3
Encoder: Gifski (not sure what version, build time 2019-1-19)
Platform: Windows 10 1703 x64

---

**Problem**

Gifski generates frames for even static recordings, results in duplicated frames and redundant file size

---

**Demo generated from same project**

Recording by `gifski-quality 100` (frames: 81, file size: 5.91MB)

![gifski-quality 100](https://i.imgur.com/JDBtWTR.gif)

[Gif link if github said it's too large](https://i.imgur.com/JDBtWTR.gif)

`Gifski-quality 100` zoom in. Note the flickering pixels.

![gifski-quality 100-4x](https://i.imgur.com/2wFuuAV.gif)

Recording by `1.0-quality 1` (frames: 19, file size: 1.97MB)

![1.0-quality 1](https://i.imgur.com/j6id38G.gif)

`1.0-quality 1` zoom in. Unchanged pixels stay the same thus it's basically 1 frame with a long timeout

![1.0-quality 1-4x](https://i.imgur.com/w7M2ob9.gif)

**Comment by kornelski** [comment]
This is done on purpose as temporal dithering.

**Comment by kornelski** [comment]
Actually, this may have been a bug. Try 0.10.1.

**Comment by byzod** [comment]
Dumb question, but where can I download the dll version for ScreenToGif?

**Comment by NickeManarin** [comment]
The DLL must be built using the source.
