### ISSUE TITLE
gifski.exe not executing on windows

### ISSUE THREAD

**Issue by joshuayoes** [ImageOptim/gifski#110]
### Issue
Downloading executing the windows exe from the download/releases page causes a window to pop up for a few frames and then close: https://gif.ski/gifski-0.10.1.zip

I am trying to create a gif from a lottie file using this library but the previous issue is preventing me from installing gifski to run the full CLI tool.
https://github.com/transitive-bullshit/puppeteer-lottie-cli

### System Info
```
OS Name	Microsoft Windows 10 Home
Version	10.0.18362 Build 18362
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	JANET
System Manufacturer	Alienware
System Model	Alienware 17 R4
System Type	x64-based PC
System SKU	0775
Processor	Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, 2601 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Alienware 1.2.4, 4/23/2018
SMBIOS Version	3.0
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Alienware
BaseBoard Product	Alienware 17 R4
BaseBoard Version	A00
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.18362.628"
User Name	JANET\gamed
Time Zone	Pacific Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	7.22 GB
Total Virtual Memory	25.4 GB
Available Virtual Memory	10.7 GB
Page File Space	9.50 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes
```

**Comment by kornelski** [comment]
I'm confused. So is it not executing, or is it executing and then crashing?

**Comment by joshuayoes** [comment]
The window will open for a brief moment and then immediately end execution

**Comment by kornelski** [comment]
> " window will open " 

gifski doesn't have a window. It's a command line application you execute in your (already open) terminal window. 

I suspect you're double-clicking the exe expecting a GUI application. There is no GUI for Windows, so what you're getting is terminal window popping up, running exe without arguments, which doesn't do anything, so the terminal closes after doing nothing.
