### ISSUE TITLE
Issue with timestamps

### ISSUE THREAD

**Issue by NickeManarin** [ImageOptim/gifski#113]
From what I could understand about the replacement of delay to timestamps, each call to `gifski_add_frame[...]` should provide the timestamp (current time, in seconds) of the frame.

So, for a list of frames with these delays:

1. 1000ms
2. 2555ms
3. 33ms
4. 299ms

The timestamps of each call to `gifski_add_frame[...]` would be:

1. 0s (since it's the first frame)
2. 1s
3. 3.555s
4. 3.588s

So you see where this is headed?

The final delays of the output gif are these:

1. 1000ms
2. 2560ms
3. 30ms
4. 30ms

It's impossible to set the delay of the last frame of every animation, so Gifski simply sets the same delay. Also, when there's only one frame, the delay is set to 20ms.

An easy way to fix this, would be to add the final timestamp as a parameter to the `gifski_finish()` method.

**Comment by kornelski** [comment]
Yeah, that's a known limitation. I didn't expect there would be a need to control timestamps so precisely, as gifski is oriented towards converting videos, and videos tend to have constant framerate.

**Comment by NickeManarin** [comment]
As a quick dirty fix, the last frame can be added twice with half of the delay. Gifski will encode both frames with the same delay.

But that increases the file size.

Can you fix this? I would change the code, but I don't understand rust or C at all.
From what I could understand, a simple f64 property passed by the `gifski_finish` to the `make_frames` method would make it work.

**Comment by NickeManarin** [comment]
So, how do you position yourself about this issue? Because it's a breaking change for people.

**Comment by kornelski** [comment]
I acknowledge it's a problem.

I think it's a low priority, because it doesn't affect conversions from video (which uses PTS natively), and it can be worked around with an extra frame. postprocessing with `gifsicle` can reduce size of that frame.

I don't think `finish` is an appropriate place to specify the extra duration. It could be a separate function call, which would be a backwards-compatible change.

In terms of implementation it can be slightly awkward, because currently every frame has its own PTS attached, so there's no place to add another one.

**Comment by NickeManarin** [comment]
> I acknowledge it's a problem.

Great! The issue is that gifs behave somewhat differently from videos.

> I think it's a low priority, because it doesn't affect conversions from video (which uses PTS natively), and it can be worked around with an extra frame. postprocessing with gifsicle can reduce size of that frame.

Yeah, it does not affect video. It only affects an image sequence conversion to gif.

> I don't think finish is an appropriate place to specify the extra duration. It could be a separate function call, which would be a backwards-compatible change.

Yes, that's a better way. 

> In terms of implementation it can be slightly awkward, because currently every frame has its own PTS attached, so there's no place to add another one.

I was peeking the code. At first I thought it would be better to add another `Option<f64>` parameter inside the `Collector` or `Writer` structs, passing it down the line to the `make_frames` method. Since I don't understand rust at all, it didn't make sense.

**Comment by byzod** [comment]
This issue is blocking https://github.com/NickeManarin/ScreenToGif/issues/611

Please make it happen <3

**Comment by kornelski** [comment]
I've added a workaround in 9c922cd53c0a710a229edeeac283592ef9f79890

It's weird, but if you squint, it makes some sense.

First frame usually starts at timestamp=0. If you put non-zero value, it'll be interpreted as the delay between the first and last frame.

**Comment by NickeManarin** [comment]
I just tested with v1.2.0 and I'm getting some issues.

Following the same set of timings from before, Gifski creates only 1 frame (the last one) with the delay set to a sum of all delays.

![image](https://user-images.githubusercontent.com/14798947/91857621-80211280-ec3e-11ea-9d84-7ffdd4d04695.png)

```
calls to gifski_add_frame_rgb(index ,,,, pts)

0, 635, 1905, 327, [IntPtr], 3.887    -> (3.887 is the sum of all delays, the timestamp of the final frame)
1, 635, 1905, 327, [IntPtr], 1
2, 635, 1905, 327, [IntPtr], 3.555
3, 635, 1905, 327, [IntPtr], 3.588
```

------------------

And if I set the timestamp of the first call to 0.299, the first frame will get a wrong delay.

![image](https://user-images.githubusercontent.com/14798947/91859167-7b5d5e00-ec40-11ea-9d45-98e94a1e491a.png)

```
calls to gifski_add_frame_rgb(index ,,,, pts)

0, 635, 1905, 327, [IntPtr], 0.299    -> (0.299 is the delay of the final frame)
1, 635, 1905, 327, [IntPtr], 1
2, 635, 1905, 327, [IntPtr], 3.555
3, 635, 1905, 327, [IntPtr], 3.588
```

**Comment by kornelski** [comment]
Thanks for the explanation.

I see I got myself into trouble with the pts->delay hack. It clashes with gifski also trying to encode rule that all pts must be in increasing order.

I'll just add an explicit config option for this :/

**Comment by NickeManarin** [comment]
Thanks. I was guessing that was happening, since the second try worked (with a delay smaller than the second timestamp).
But I didn't understand why the first frame was getting a delay of 710ms...

**Comment by kornelski** [comment]
That was 1 - 0.299. pts of first frame is subtracted from all later frames (they're shifted in time to loop nicely)

**Comment by NickeManarin** [comment]
> I'll just add an explicit config option for this :/

Do you think this is easy/quick to fix?

**Comment by kornelski** [comment]
Yes, it should be relatively easy to add

**Comment by NickeManarin** [comment]
Also, is there any way to add the version number of the DLL?
Product version and file version.

![image](https://user-images.githubusercontent.com/14798947/92162776-16089900-ee09-11ea-8b10-114b185c1d01.png)

**Comment by NickeManarin** [comment]
Btw, commenting [line 290](https://github.com/ImageOptim/gifski/blob/main/src/lib.rs#L290) and removing the usage of `pts_in_delay_units` from [line 300](https://github.com/ImageOptim/gifski/blob/main/src/lib.rs#L300) did the job for me.

![image](https://user-images.githubusercontent.com/14798947/92166586-38051a00-ee0f-11ea-95bb-581f14a96ceb.png)

**Comment by kornelski** [comment]
This should be fixed now
