### ISSUE TITLE
Feature Request: Target file size / Gifsicle integration

### ISSUE THREAD

**Issue by LesterCovax** [ImageOptim/gifski#115]
I've written some wrapper scripts to attempt the automation of GIF creation from any format, into something usable on social media (i.e. under 15-20 MB), but often find myself having to manually tweak things with Gifsicle.  That includes trying different levels of lossiness or dropping the resolution.

There appears to be some form of integration between Gifski and Gifsicle, but I'm not sure whether it's just a placeholder or is actually functional (didn't see documentation).  Again, I could continue to create wrapper scripts to get it to a working state where it just keeps recreating the GIF using different parameters until it's below a target size, but thought I'd suggest it as a feature.

**Comment by kornelski** [comment]
Gifsicle is integrated into gifski when you use quality < 100.

GIF format is awful and unsuitable for target file size. It's not possible to do any better than encode multiple times and see what comes out.

**Comment by LesterCovax** [comment]
Gotcha.  Guess I was just hoping I'd be able to pass Gifsicle-specific flags, such as `-O3`/`--resize-height`/`--lossy=`.  Should I assume that Gifski's `quality` is just inversely proportional to Gifsicle's `lossy`?  I initially assumed there was a special way to utilize Gifsicle within Gifski since I think there was a Gifsicle build flag mentioned somewhere.

Yeah, been realizing that lately converting from converting mkv/webm/mp4 to GIF...it's so hit or miss.  Earlier I had a 4.3MB MP4 (826x426, 17s, 33fps) balloon to 86MB when converted to a GIF.  It's just an odd time for GIFs, as many sites will just convert them to MP4/WebM/Gifv, or support them in the first place.  APNG support is also a crapshoot.

Cheers for the info, and your work on gifski!

**Comment by kornelski** [comment]
Gifski doesn't integrate with gifsicle command line, but via C API, so these flags don't exist. It doesn't replicate all of gifsicle's features, only lossy compression.

If you want to use -O3, the best option is to make a GIF with 100% quality, and then recompress separately.
