### ISSUE TITLE
Self-containted release tarballs

### ISSUE THREAD

**Issue by Barthalion** [ImageOptim/gifski#12]
For build tools that disallow networking access during compilation, it would be useful if tarballs with source code contained all dependent libraries.

**Comment by Barthalion** [comment]
Looks like there is [cargo-vendor](https://github.com/alexcrichton/cargo-vendor), not sure if there is anything like that in cargo itself.

**Comment by phw** [comment]
I second this, just ran into this issue when trying to build a Flatpak which was supposed to also build containing the gifski binary on Flathub, which runs sandboxed builds without network access.

**Comment by pornel** [comment]
This is a standard Rust/Cargo project and it doesn't do any network requests by itself, so I don't think there's anything I need to do here. It's rather a matter of getting Cargo to build the way you want.

I never needed offline builds so I'm not familiar with the procedure. `cargo-vendor` is written by Cargo's author, so it may be a good solution.

If you're having trouble with making Cargo cooperate, please leave feedback:

https://internals.rust-lang.org/t/what-do-rust-tools-need-from-the-build-system/5975

Rust team is currently working on improving Cargo integration and they're seeking feedback.
