### ISSUE TITLE
Compile fails

### ISSUE THREAD

**Issue by df1paw** [ImageOptim/gifski#13]
Hi.
I just tried to compile it from git. But it fails with the following error:
`andreas@Nbk:~/src/gifski$ cargo run --release --features=openmp
# Downloading openmp-sys v0.1.1
   Compiling glob v0.2.11
   Compiling num_cpus v1.7.0
   Compiling ansi_term v0.9.0
   Compiling imgref v1.3.0
error: no method named `min` found for type `usize` in the current scope
  --> /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/imgref-1.3.0/src/iter.rs:75:56
   |
75 |             self.buf_left = &self.buf_left[self.stride.min(self.buf_left.len()-1)..];
   |                                                        ^^^
   |
   = note: the method `min` exists but the following trait bounds were not satisfied: `usize : std::iter::Iterator`

error: aborting due to previous error

error: Could not compile `imgref`.
Build failed, waiting for other jobs to finish...
error: build failed
andreas@Nbk:~/src/gifski$ #
`

**Comment by pornel** [comment]
You need newer version of Rust
