### ISSUE TITLE
gif to gif conversion support

### ISSUE THREAD

**Issue by thewayur** [ImageOptim/gifski#131]
i have gifs which has loop issue,
or in simple words can i convert gif to fix loops?
thanks.

**Comment by kornelski** [comment]
No, this tool isn't for such things. Use `gifsicle`.

**Comment by thewayur** [comment]
> No, this tool isn't for such things. Use `gifsicle`.

yes i m using it,
pls can u gimme command from gif to gif conversion via gifsicle?
