### ISSUE TITLE
Artifacts present in 1.2.0 that are not in 1.1.1

### ISSUE THREAD

**Issue by justinruggles** [ImageOptim/gifski#132]
When converting a MP4 source to GIF with gifski 1.2.0 commandline program for mac, I get some jarring visual artifacts that are not present when converting the same file with gifski 1.1.1.

Input is 1080p@24FPS. I get the same types of artifacts with different output sizes and qualities.

This is a screenshot of the GIF playing in Chrome. I get similar artifacts with any other viewer.

![image](https://user-images.githubusercontent.com/108822/89936484-b17b6500-dbe1-11ea-86a3-aee11fe944a8.png)

**Comment by kornelski** [comment]
Can you share the input movie you're converting?

**Comment by justinruggles** [comment]
I uploaded the input to Vimeo. https://vimeo.com/446999185/2e7693bc09
The original source is available for download at that page.
I converted it using the gifski 1.2.0 binary for mac supplied in the release download on github:

```
gifski source.mp4 -o 1.2.0.gif -r 24 -Q 100 -W 640
```

**Comment by justinruggles** [comment]
https://storage.googleapis.com/tc-testing/ruggles/1.2.0.gif

**Comment by kornelski** [comment]
Thanks. It looks like a bad compile of the Mac version. I've re-uploaded freshly-built 1.2.0.

**Comment by justinruggles** [comment]
I just downloaded the release again and I get the same one (MD5 matches for the old and current gifski-1.2.0.tar.xz)

**Comment by justinruggles** [comment]
Nevermind. Maybe it was Chrome... I just downloaded the new one with curl and the MD5 is different.

**Comment by justinruggles** [comment]
Well, I'm still getting the same mac binary. (MD5 = 9b0a844aafd85895efd923812c927ff6)

**Comment by justinruggles** [comment]
I built my own mac binary, and I can confirm that it does not have the same issue as the one in the release.

**Comment by kornelski** [comment]
Fixed in 1.2.2
