### ISSUE TITLE
it can't access directory what have the empty space

### ISSUE THREAD

**Issue by onanana** [ImageOptim/gifski#133]
i'm using gifski for windows cli

it can't access directory what have the empty space

like this

gifski -o c:\program files\file.gif c:\program files\frame*.png

when directory have the empty space like program files, gifski got error

**Comment by DumbJoe** [comment]
>Arguments on command line must be in quotes. "program files"

Then you get this nice error: The path contains a literal "*" character. If you want to select multiple files, don't put the special wildcard characters in quotes.

**Comment by kornelski** [comment]
You can mix and match:

```bash
gifski -o c:\"program files"\file.gif "c:\program files\"frame*.png
```
