### ISSUE TITLE
Cut-off results

### ISSUE THREAD

**Issue by CanRau** [ImageOptim/gifski#136]
Just tried the CLI, installed 1.2.0 via `brew` on MacOS 10.14.6

I was really confused, running this command `gifski -o gifski-test.gif WaterOnlyFrame*.png`, which showed like this in the Finder preview & Preview app

![screenshot](https://user-images.githubusercontent.com/5196971/93492492-7c44ef80-f8d0-11ea-92dd-b168f44414a1.png)

The png frames are 2418x1482 in size and at the bottom not cut like this. Then, while writing this issue I realized that the result is actually less cut than in Finder, though the last drop is still cut-off like shown here

![gifski-test](https://user-images.githubusercontent.com/5196971/93491585-7b5f8e00-f8cf-11ea-9891-69ebe96b580e.gif)

& easier to catch in this slower one `gifski -o gifski-test_fps2_small.gif -r 2 WaterOnlyFrame*.png`

![gifski-test_fps2_small](https://user-images.githubusercontent.com/5196971/93493353-700d6200-f8d1-11ea-9ea6-ec5f8f57a006.gif)

I would've expected it to be similar to the source frames in size, not cut off & better in colors, though I understand that the last one might be an issue with the translucent watercolory effect, as another one I tried is good in colors, just really small and cut off at the bottom as well, what am I doing wrong? 🤔

I thought it'll give me the same dimensions but I'm able to change that with the args opposed to it massively shrinking it and I have to "keep" it the expected size by setting the args.

Original png Frames
![WaterOnlyFrame1](https://user-images.githubusercontent.com/5196971/93491609-84505f80-f8cf-11ea-86d2-7ef760b9776e.png)
![WaterOnlyFrame2](https://user-images.githubusercontent.com/5196971/93491649-8f0af480-f8cf-11ea-894c-f06583df8c71.png)
![WaterOnlyFrame3](https://user-images.githubusercontent.com/5196971/93491667-96ca9900-f8cf-11ea-965e-e52c44df9c55.png)

**Comment by Norway174** [comment]
Can confirm this happens for me in Windows 10 too.

Downloaded Gifski today, version says 1.2.0.

And this is the command I used:
`gifski -o C:\tmp\base.gif C:\tmp\0*.png`

I also tested this command:
`gifski -W 800 -H 600 -o C:\tmp\base.gif C:\tmp\0*.png`

Which produced this:
![base](https://user-images.githubusercontent.com/4808657/94380782-3c370580-0137-11eb-980d-a336c58a6be6.gif)

The size is only 400x106, while the source images are all in 800x600.
![0001](https://user-images.githubusercontent.com/4808657/94380807-5d97f180-0137-11eb-9ac7-91981c2b2e9a.png)

**Comment by kornelski** [comment]
Thanks for the report. It looks like a bug indeed. 1.2.0 introduced new optimization that stores partial frames.

**Comment by kornelski** [comment]
Fixed

**Comment by CanRau** [comment]
Seems to work 😍🥳
Thank you 🙏❣️
