### ISSUE TITLE
Variable framerate

### ISSUE THREAD

**Issue by NickeManarin** [ImageOptim/gifski#14]
Is it possible to create a variable framerate gif with this tool?

Something like the `-concat` option available with `FFmpeg`.

**Comment by pornel** [comment]
It's possible programmatically. Also if you manage to compile it with video support, it will use exact timestamps (PTS) from the video.

From command line, nope. You could create a gif and then edit the timings with another tool (like gifsicle).

**Comment by NickeManarin** [comment]
Yes, command line. I forgot to specify.

Are you accepting feature requests/do you have plans to implement this feature? 

If not, you can close this issue, thanks anyway.

**Comment by pornel** [comment]
What's the use-case for this feature? Can it have non-cumbersome UI?

**Comment by NickeManarin** [comment]
I'm trying to integrate this project with my app. The use case is simple, if the user wants to use a third party encoder, he just need to download one that is supported, such as FFmpeg.

As far as I can tell, this project is only distributed with a executable and I'm not using C or Rust. That's why I'm asking for this feature for the CLI.

**Comment by pornel** [comment]
I see. Maybe consider using the API? Building it shouldn't be hard:

1. [Install Rust](https://www.rust-lang.org/install.html) (when you already have Visual Studio it's quick)

2. In gifski project folder run:

    ```sh
    cargo build --release --lib
    ```

    and that will make you `target\release\gifski.dll` that your app can use.

3. [The API is just 4 functions](https://docs.rs/gifski/0.6.2/gifski/c_api/index.html), which you can call via P/Invoke ([similar to this](https://github.com/ImageOptim/libimagequant/blob/master/libimagequant.cs#L46))

**Comment by NickeManarin** [comment]
Yes, I'm aware that I could use the lib. But this would require me to distribute it with my app. Even if the user does not want it. (unless I can download it from somewhere else)

My app is a single .exe that does not require installation, that's why I'm trying to follow the same usage pattern as the FFmpeg.

**Comment by pornel** [comment]
If your goal is single exe, then static linking is also an option. 

If you want to reduce distribution size, then it is extra 500KB zipped, and I can't do much about it.

**Comment by NickeManarin** [comment]
I'm switching to the lib and I already got the dll in hands. But I'm always getting `false` and a zero length file with the `gifski_write` method. GetLastError gives me 0.

I'm using this structure (pseudo-code):

```
var handle = gifski_new(GifskiSettings); //always returns non-zero IntPtr.

//new thread
//for all frames
gifski_add_frame_png_file(IntPtr handle, uint index, string path, ushort delay); //always returns true.

gifski_end_adding_frames(IntPtr handle); //always returns true.
//end of new thread.

bool gifski_write(IntPtr handle, string destination); //always returns false.
gifski_drop(IntPtr handle);

```

Looking at the lines of `gifski_write` it appears that the app reaches this line and returns false:

```
if let Some(writer) = g.writer.take() {
        return writer.write(file, &mut NoProgress {}).is_ok();
}
```

Any idea of what's happening? (Or do you need more info?)

**Comment by kornelski** [comment]
OK, boolean error information is not good enough. 

I've changed it to an enum in 6f431e8958af4e608a568847d69c33f7f4c97d9a.

**Comment by NickeManarin** [comment]
Thank you :)

With this new version, I'm getting **14 - GifskiOther** while adding a png frame (also when using gifski_write).

I'm hope that I'm using the correct p/invokes:

```
private delegate IntPtr NewDelegate(GifskiSettings settings);
private delegate GifskiError AddPngFrameDelegate(IntPtr handle, uint index, string path, ushort delay);
private delegate GifskiError EndAddingFramesDelegate(IntPtr handle);
private delegate GifskiError WriteDelegate(IntPtr handle, string destination);
private delegate void DropDelegate(IntPtr handle);

private static readonly NewDelegate New = (NewDelegate)FunctionLoader.LoadFunction<NewDelegate>(UserSettings.All.GifskiLocation, "gifski_new");
private static readonly AddPngFrameDelegate AddPngFrame = (AddPngFrameDelegate)FunctionLoader.LoadFunction<AddPngFrameDelegate>(UserSettings.All.GifskiLocation, "gifski_add_frame_png_file");
private static readonly EndAddingFramesDelegate EndAddingFrames = (EndAddingFramesDelegate)FunctionLoader.LoadFunction<EndAddingFramesDelegate>(UserSettings.All.GifskiLocation, "gifski_end_adding_frames");
private static readonly WriteDelegate Write = (WriteDelegate)FunctionLoader.LoadFunction<WriteDelegate>(UserSettings.All.GifskiLocation, "gifski_write");
private static readonly DropDelegate Drop = (DropDelegate)FunctionLoader.LoadFunction<DropDelegate>(UserSettings.All.GifskiLocation, "gifski_drop");
```
(PS: I'm using delegates with a Function Loader to be able to specify a custom location for the dll

**Comment by NickeManarin** [comment]
Forget it. It magically started working after closing VS and opening again without changing anything. :P

**Comment by kornelski** [comment]
Phew. The "other" error would have been hard to track :)
