### ISSUE TITLE
Off-color artifacts on some frames

### ISSUE THREAD

**Issue by scribblemaniac** [ImageOptim/gifski#143]
Gifski produces noticeable artifacts that flicker on the screen for a a frame or two with a very specific video I tested. I have not seen this behaviour with any other videos, though I admit I don't use it too often currently. The original video can be viewed [on Youtube](https://www.youtube.com/watch?v=5Ehd4cFEvnQ) and there is a download link for it in the description. I then extracted the first 10 seconds worth of frames (`ffmpeg -i <path_to_video> -t 10 %04d.png`) and encoded them with gifski 1.2.0 (`gifski *.png --fps 24 --output out.gif`). You can download the result [here](https://mega.nz/file/BrQgwZBA#CHKDHym2QBAmM7PieOAhOEw_sZtLFu50r0Y0HIvPur8). And here are a couple of snapshots for quick referencing:
![0060](https://user-images.githubusercontent.com/3461051/95643871-5a71ff00-0a6f-11eb-8f67-fb45ca71da16.png)
![0117](https://user-images.githubusercontent.com/3461051/95643887-6fe72900-0a6f-11eb-8a8e-efc190c6ee04.png)

As you can see, the gif occasionally flickers with off-color artifacts. They are most noticeable in the bright spots as above, but it also seems to be occurring elsewhere too. Look for example above and to the left of the brightest spot in this frame:
![0118](https://user-images.githubusercontent.com/3461051/95643921-d409ed00-0a6f-11eb-97e0-841e4b478643.png)

This issue has been present since at least 0.8.5, so it is definitely not a duplicate of #132. It may be a duplicate of #30, although based on the screenshot it looks quite different. I hope that this information is enough for this issue to be reproduced and fixed, but if not please let me know if there is any other information you would like me to provide..

**Comment by kornelski** [comment]
This is fixed in 1.4.0.

**Comment by scribblemaniac** [comment]
It looks much better now, testing with this example at least. I'm guessing that's the result of the denoising? Anyway great work, thanks! :1st_place_medal:

**Comment by kornelski** [comment]
It was a weird side effect of "if dithered pixel is more different than the difference with the background, then keep the background." which turned out to create lots of unexpected edge cases.

This animation is a very tough case anyway. It has lots of gradients, which are tough for 8-bit palette. Then it has blocky artifacts from the video codec, and posterization from low color palette happens to enhance edges of these blocks.
