### ISSUE TITLE
Only the top of the gif looks halfway like the source frames

### ISSUE THREAD

**Issue by Boscop** [ImageOptim/gifski#149]
I followed the guide.
At first I extracted frames from my vid using ffmpeg:
```
> ffmpeg -i final.mp4 -vf fps=10,scale=320:-1:flags=lanczos frame%04d.png
> gifski -o final.gif frame*.png
```

The input frames all look kinda like this one:

![image](https://user-images.githubusercontent.com/535593/98485491-119c9a00-2217-11eb-835d-155aed9f1f60.png)

The gif's frames all look kinda like this one:

![image](https://user-images.githubusercontent.com/535593/98485493-1a8d6b80-2217-11eb-8527-639663b62edc.png)

I uploaded the full gif here: https://imgur.com/a/1empBY8
The gif is all black, except for the area near the top (and even that has some noise towards the black area).

Any idea why? Btw, I had installed it via cargo.
OS: Win 8.1

If you want the full source frames and gif for debugging purposes, here is a wetransfer link (I think it stays active 1 week):
https://we.tl/t-26JcGMGtha

Btw, interestingly, even though that black area is black throughout the gif, in the Windows preview when I delete it, it's not all black, but noisy:

![image](https://user-images.githubusercontent.com/535593/98485588-d2bb1400-2217-11eb-983d-737087886d3f.png)

**Comment by kornelski** [comment]
Thanks for the report. This is indeed a bug in the encoder. I'll revert to an earlier version.

https://github.com/image-rs/image-gif/issues/91

**Comment by kornelski** [comment]
BTW, setting `--quality=90` should work around this, since that will encode using gifsicle encoder instead of piston-gif encoder.

**Comment by kornelski** [comment]
This has been fixed
