### ISSUE TITLE
Managing alpha from PNG

### ISSUE THREAD

**Issue by AiZ** [ImageOptim/gifski#15]
Hello,

First, thanks for such a cool tool!

I was trying to convert the rotating cube from [http://davidmz.github.io/apng-canvas/](http://davidmz.github.io/apng-canvas/).

If I extract rgba PNGs, I get this:
![cube](https://user-images.githubusercontent.com/3725758/33946180-621d1a76-e021-11e7-9e83-51a6e01b3f04.gif)

Is it possible to (kinda) keep the original transparency or not?

Best regards,

    AiZ

**Comment by pornel** [comment]
I can fix it so that it renders properly, but it will be limited to 256 colors per frame, because GIF can't make an opaque pixel transparent without resetting background to all-transparent.

**Comment by AiZ** [comment]
Ok, got it. I suppose your tool is aimed toward more true colours movies-like animated GIF than animation.
Possibly you could add a switch for an option to deal with transparent input but if it ends with ffmpeg/gifsicle-ish results, it perhaps doesn't worth the hassle.

Anyway, thanks again for your dedication.

**Comment by pornel** [comment]
I've fixed that in v0.7, now it looks like this:

![apng](https://user-images.githubusercontent.com/72159/33955134-6d4e9922-e032-11e7-9803-45d19952f2e7.gif)
