### ISSUE TITLE
Single frame encodes are broken after v1.2.2

### ISSUE THREAD

**Issue by rzumer** [ImageOptim/gifski#153]
[test.zip](https://github.com/ImageOptim/gifski/files/5639047/test.zip)

I use the C API to encode RGB24 frames from the clip above (it is probably not clip-dependent, but sending it just in case). When only one frame is sent to Gifski (frame number 0, pts 0) the output is empty in recent versions. 1.2.2 works as expected (produces a single frame encode).

**Comment by kornelski** [comment]
This is fixed in the latest version
