### ISSUE TITLE
Problem with artifacts

### ISSUE THREAD

**Issue by RaedsLab** [ImageOptim/gifski#157]
First of all, thank you for the amazing project.

I have been trying to encode a countdown timer from a list of PNG files that look like this:

![frame_00_delay-1s](https://user-images.githubusercontent.com/1442690/104085455-e9014280-524f-11eb-92df-e5f5cacb7539.png)

With each frame taking a second I use the `cli` like this: 

```sh 
gifski --quality 100 --width 300 --height 80  --fps 1 --output file.gif frame_*.png

``` 

However my output seems to have artifacts: 

![file](https://user-images.githubusercontent.com/1442690/104085446-c707c000-524f-11eb-8388-ae8f56f71e02.gif)

Here are what some of the frames look like: 

![image](https://user-images.githubusercontent.com/1442690/104085497-3da4bd80-5250-11eb-9fd2-dbc5ad61efd3.png)

Any clue one where I should start looking to help fix this?

Here is a tar.gz file of the original PNG frames ([link](https://drive.google.com/file/d/1QBSO5fPSfkT9l7Q-zGqhlWI8uiWufL1L/view?usp=sharing))

**Comment by kornelski** [comment]
Thanks! I've fixed it in v1.2.6
