### ISSUE TITLE
The top of some frames are cut off

### ISSUE THREAD

**Issue by TPGamesNL** [ImageOptim/gifski#158]
Input:
[input.zip](https://github.com/ImageOptim/gifski/files/5792754/input.zip)
Command: 
`gifski input/*.png --fps 14 --quality 100 --output output.gif`
Output:
https://imgur.com/a/FUFCzQ2
Frames 2, 15 and 19 have a few rows of pixels cut off:
![frames](https://user-images.githubusercontent.com/29547183/104126411-a0837b00-535c-11eb-8f1b-27f54bc8c413.png)

gifski v1.2.4

**Comment by kornelski** [comment]
Why are you drawing racist frogs? Ewww.

**Comment by TPGamesNL** [comment]
Pepe by itself is usually not considered racist (which is also my opinion, https://www.adl.org/education/references/hate-symbols/pepe-the-frog), but because of its popularity it has previously been associated with racist opinions / remarks. I respect your decision to keep this thread closed because of these associatons, but I'd prefer to have it re-opened, as the character itself wasn't created for these wrong purposes. If you decide to keep the thread closed, I'll see if I can recreate the issue with another set of images.

**Comment by kornelski** [comment]
The bug is fixed, btw.
