### ISSUE TITLE
Question: Is there a way to pipe the output instead of creating a file? 

### ISSUE THREAD

**Issue by RaedsLab** [ImageOptim/gifski#159]
## Question 

When using the cli, I want to pipe the output of `gifski` so I can chain different tools. 

For example `gifsicle` does this really well, if you omit the `--output` option it will just return the gif in the stdout.

Is this something doable with `gifski` ?

**Comment by kornelski** [comment]
Currently it's not possible. It would be easy to add: 

https://github.com/ImageOptim/gifski/blob/main/src/bin/gifski.rs#L195 

like so: 

https://github.com/kornelski/cavif-rs/blob/main/src/main.rs#L167

**Comment by RaedsLab** [comment]
Thank you for clarifying that! With my abysmal rust knowledge I wasn't able to bodge it together. 😄 

Should I create a feature request?

**Comment by kornelski** [comment]
Done `-o -`
