### ISSUE TITLE
A way to set less than 1 fps or non whole number frame rate?

### ISSUE THREAD

**Issue by DumbJoe** [ImageOptim/gifski#161]
This may be related: https://github.com/ImageOptim/gifski/issues/31 but I wanted to make a give and have the file play back at a slower rate, like once every ten seconds like slideshow of sorts in powerpoint, except it won't let me enter anything less than one, no decimal value is valid either like 0.1 for the mentioned one frame every ten seconds.... May as well give us an option to do 0.0001 of a frame rate just in case someone here decides he wants to do a slow ass slideshow presentation....with pictures....

**Comment by kornelski** [comment]
Currently there isn't a way to specify this. If you add many identical frames, gifski should be smart enough to deduplicate them and make one frame that is displayed for longer.

**Comment by kornelski** [comment]
Fractions are supported. The --fps 0.001 in the command line should work.
