### ISSUE TITLE
converting transparent png sequence into gif results in strange flashing

### ISSUE THREAD

**Issue by HexCodeFFF** [ImageOptim/gifski#165]
I'm not sure exactly what is causing this behavior
this is what the input looks like
![image](https://user-images.githubusercontent.com/35177464/108378963-13d5a380-71cb-11eb-8853-e977066b8ef2.png)
this is the resulting output
![image](https://cdn.discordapp.com/attachments/803807761527734284/811980823808442398/DceYwbeV.gif)

The command i'm running in the console looks like this:
`('gifski', '--quiet', '--fast', '-o', 'temp/DceYwbeV.gif', '--fps', '30.0', '--width', '1000', 'temp\\NejcYoeL000000001_rendered.png', 'temp\\NejcYoeL000000002_rendered.png', 'temp\\NejcYoeL000000003_rendered.png',` with 60 more images passed automatically with python's glob module. the strange format here is due to the format that is best used to safely call console commands from python.

**Comment by kornelski** [comment]
This bug looks suspiciously specifically affecting just the text, and doesn't look like anything related to GIF compression.

Are you sure this folder doesn't contain two sets of images — before and after adding the text?

**Comment by HexCodeFFF** [comment]
I'll close this since it's _very_ likely what you said was true and I haven't experienced this issue ina  while.
