### ISSUE TITLE
Issue when using with gganimate - flashing green background in gif

### ISSUE THREAD

**Issue by LukasWallrich** [ImageOptim/gifski#169]
Quite a few people have been experiencing issues when using gifski to render animations created by gganimate - they contain a background that flashes in green - see below and the whole thread here: https://github.com/thomasp85/gganimate/issues/431 - would be great if you could help fix that issue.

![](https://i.imgur.com/OhuHFOs.gif)

**Comment by kornelski** [comment]
I think I've already fixed this bug. Are you using the latest version?

**Comment by LukasWallrich** [comment]
Thanks for responding, but I am getting very confused - I am using gifski on Windows through the gifski R package (most recent version, 0.8.7.1). When I installed gganimate, that was installed and gifski set up. I am now not sure how to check the underlying gifski version, let alone update it. Do you know, or is that a question to those package developers?

**Comment by kornelski** [comment]
I don't know. I have nothing to do with the R package.

**Comment by LukasWallrich** [comment]
> I don't know. I have nothing to do with the R package.

Ok, I am trying to pursue this further with the package authors: https://github.com/r-rust/gifski/issues/16

**Comment by LukasWallrich** [comment]
It only occurs with recent version of the r-gifski package - so it is probably about something else altogether. @kornelski, I will close this for now - thanks for your help.

**Comment by kornelski** [comment]
To be clear, this is certainly a bug in gifski. It's just that I expect it to happen only in versions < 1.4.

**Comment by jeroen** [comment]
Yes the R package still uses gifski 0.8.7 (I haven't had time to update the R bindings to your new api).

**Comment by kornelski** [comment]
This was because the palette can contain multiple transparent entries, but GIF supports only one transparent entry. So pixel data needs to be normalized.

https://github.com/ImageOptim/gifski/commit/e7d555ac60a3682924ec8c96ed00687d851421f8

**Comment by jeroen** [comment]
@kornelski I am trying to port the bindings to gifsi 1.4.3, using your simplified API, however it doesn't seem to work anymore.

I call `gifski_add_frame_png_file` in a loop and then `gifski_finish` in the end. Everything returns `GIFSKI_OK`, however the final gif only seems to contain twice the initial frame and nothing else.

**Comment by jeroen** [comment]
Ok never mind I figured it out! Something changed in the API call to `gifski_add_frame_png_file` wrt the pts parameter.
