### ISSUE TITLE
Multithreading?

### ISSUE THREAD

**Issue by soshimee** [ImageOptim/gifski#177]
Why not use multithreading or GPU? It's still pretty quick, but I have 20 threads in my CPU, so it would be even quicker. If it's possible for GPU to do this, maybe it would be even faster.

**Comment by kornelski** [comment]
It already has a dozen threads and everything that could be multi-threaded, is. 

Unfortunately, encoding of GIF frames as a deltas is necessary to achieve reasonable quality and efficiency, but this makes every frame depend on every previous frame, which serializes the whole process.
