### ISSUE TITLE
Feature request: small colour diference ignore

### ISSUE THREAD

**Issue by T0biasCZe** [ImageOptim/gifski#179]
Often the gif layers repeat pixels even when they are unchanged because of the source compression because it has few numbers different rgb. to fix this there could be some different flag (for example gifski ... --diference 2 ...) when the pixel colour was 195 132 55 and on the next frame its 195 130 57 it would ignore the change and keep it as unchanged pixel. it could reduce the size a bit

**Comment by kornelski** [comment]
This is already implemented, and the quality setting controls this.

**Comment by T0biasCZe** [comment]
> and the quality setting controls this.

Set the quality to 2, the pixels are still repeated 🙃

**Comment by kornelski** [comment]
Can you share the input anim you're testing it on?

**Comment by T0biasCZe** [comment]
forgot about this, sure
the only changing part is the rotating mario at the top, but when you zoom in, there is a noise everywhere in the gif
[Sonic meme.zip](https://github.com/ImageOptim/gifski/files/6950949/Sonic.meme.zip)

**Comment by kornelski** [comment]
Thanks. I've released 1.5.0 with a more aggressive diffing.
