### ISSUE TITLE
Video support is permanently disabled in this executable with CLI version

### ISSUE THREAD

**Issue by NickeManarin** [ImageOptim/gifski#18]
Hi, I`m getting this error while running the same command that worked fine with v0.6.0:

```
Command:

--quality 50 --fps 8 "C:\Users\Usr\AppData\Local\Temp\Frames\*.png" -o "C:\Users\Usr\Desktop\1.gif"

Result:

Error: Video support is permanently disabled in this executable.

To enable video decoding you need to recompile gifski from source with:
cargo build --release --features=video

Alternatively, use ffmpeg command to export PNG frames, and then specify
the PNG files as input for this executable.
```

Not sure what changed from v0.6.0 and v0.7.0...

**Comment by phw** [comment]
How did you install gifski? From source, using the official binaries here on Github or some other package?

**Comment by NickeManarin** [comment]
Downloading it from: https://gif.ski/gifski-0.7.0.zip

**Comment by pornel** [comment]
`"*"` means one file containing literally the asterisk character. `*` unquoted means any file.

**Comment by NickeManarin** [comment]
Uh, but why does this message about "video support" appears?

**Comment by pornel** [comment]
Because it supports frames if there is > 1 file, and video if files == 1

**Comment by pornel** [comment]
I've made it explain itself in dd6899520231933a2b376ddd13308086f502c263

**Comment by NickeManarin** [comment]
I'm using double quotes to support paths with spaces. [I tried to scape the spaces using other methods](https://superuser.com/questions/279008/how-do-i-escape-spaces-in-command-line-in-windows-without-using-quotation-marks#), without success. Do you know any other way to circumvent this issue?

**Comment by kornelski** [comment]
Quote everything except the `*` character:

```sh
gifski "path with spaces and *asterisks*/"*".extension with spaces"
```

Note that backslash and quote escaping on Windows is *bizarre* https://msdn.microsoft.com/en-us/library/windows/desktop/bb776391(v=vs.85).aspx

**Comment by sergeevabc** [comment]
Dear @kornelski, indeed, what’s going on with Gifski CLI?
Being a Windows user, I downloaded the latest binary 1.4.0, then
`gifski -o file.gif frame*.png` output the error as follows
```
error: Video support is permanently disabled in this executable.         
                                                                         
To enable video decoding you need to recompile gifski from source with:  
cargo build --release --features=video                                   
or                                                                       
cargo install gifski --features=video                                    
                                                                         
Alternatively, use ffmpeg command to export PNG frames, and then specify 
the PNG files as input for this executable.                              
```

**Comment by kornelski** [comment]
I haven't managed to get ffmpeg working on Windows.
