### ISSUE TITLE
Gifski mistakes JPGs for PNGs when --fast-forward is used

### ISSUE THREAD

**Issue by FridgeRacer** [ImageOptim/gifski#188]
I'm trying to convert a moderate handful of JPG files to an animated gif, and I want it to be sped up.
My attempts went as such:

```
[ridge@Ridge-Arch gif]$ gifski -r 50 -Q 70 --fast-forward 2 img*.jpg -o a.gif
error: Speed doesn't apply to PNG files as input, use fps only

[ridge@Ridge-Arch gif]$ gifski -Q 70 --fast-forward 2 img*.jpg -o a.gif
error: Speed doesn't apply to PNG files as input, use fps only
```

Unfortunately gifski thinks my JPG files are PNGs, and won't let me continue.
This is using the gifski 1.4.0 package from Arch community repository: https://archlinux.org/packages/community/x86_64/gifski/

Anything I could do to troubleshoot this further, or work around? Thanks in advance.

I tried building gifski from source to test that way, but getting Cargo to not fail when building ffmpeg-sys-next was a bit outside the time on my hand and "expertise".

**Comment by kornelski** [comment]
JPEG is not supported on purpose: https://github.com/ImageOptim/gifski/issues/66#issuecomment-682165192

**Comment by FridgeRacer** [comment]
Love it. Thanks for the quick response! 😉
