### ISSUE TITLE
Problem with Gifski

### ISSUE THREAD

**Issue by tpkn** [ImageOptim/gifski#19]
![fail](https://user-images.githubusercontent.com/18248992/34457437-3f0de3e6-edc1-11e7-9d3f-7a560ccde201.jpg)

Any idea why this happens? (default settings)

**Comment by pornel** [comment]
This is not enough information to tell.

**Comment by tpkn** [comment]
Win7 x64 with all updates. 
Something else?

**Comment by pornel** [comment]
I've never used ScreenToGif. The error message only contains a vague reference to a private method in that app, without explaining what was encoded, or anything technical about gifski or its output.

I could help if you could reproduce the problem without using ScreenToGif, or at least be able to somehow collect arguments sent to and outputs printed by the gifski.exe command run by ScreenToGif.

**Comment by pornel** [comment]
@NickeManarin could you help here? e.g. capture stderr and display it in the alert box? or detect root cause of the failure yourself and display specific recovery instructions.

**Comment by tpkn** [comment]
Yep, just tested bare Gifski and it works great. Looks like some issue within ScreenToGif...

**Comment by NickeManarin** [comment]
I believe that it's [this issue](https://github.com/ImageOptim/gifski/issues/18). It works with v0.6 but doesn't work with any newer release of Gifski. 

I have now included the stderr on the exception viewer of ScreenToGif and it will be available with v2.11.1.
