### ISSUE TITLE
Code stalls after the 4th frame is added with 'add_frame_rgba'

### ISSUE THREAD

**Issue by lilBunnyRabbit** [ImageOptim/gifski#190]
Hi! I have been trying to debug this for hours now and I cant really find what the problem is...

I'm having issues with adding frames to the **collector**. It works great for the first 3 frames, it generates the gif without any issues but if I try to add more than 3 frames the whole thing just gets stuck and never stops... no errors, nothing. I tried it with threads and also with just dropping the collector and the result is always the same. Am I doing something really stupid here or ?

Snippet of the code:
```rust
let settings = Settings {
  width: Some(dimensions.0),
  height: Some(dimensions.1),
  quality: 100,
  fast: true,
  repeat: Repeat::Infinite,
};
let (collector, _) = gifski::new(settings).unwrap();

let frames: Vec<Vec<ImgVec<RGBA8>>> = ...;

for (i, frame) in frames.iter().enumerate() {
  let timestamp = i as f64 * 0.06;
  collector.add_frame_rgba(i, frame, timestamp).unwrap();
}

drop(collector);
```

Thanks for the help I really didn't know where else to look...

**Comment by kornelski** [comment]
This is intentional. It buffers only a few frames and then waits for you to start writing them to a file from another thread.

**Comment by lilBunnyRabbit** [comment]
Thank you! I missed that it works now.
