### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by soshimee** [ImageOptim/gifski#192]
Gifski filled up all 32GB of RAM and ended up getting killed by OOM. This obviously isn't desirable, especially to people who don't have as much RAM.

**Comment by kornelski** [comment]
Can you provide more information?

**Comment by soshimee** [comment]
Memory usage gradually goes up when directly processing videos, not frame by frame.

**Comment by kornelski** [comment]
Does it happen with any particular video file? What size of video frames are you encoding? How many cores you have?

gifski is buffering only as many frames as there are CPU cores, so such high usage is unexpected.

**Comment by soshimee** [comment]
It is an MP4 file. My video should be <10MB (only a minute long). I am not sure, but I will test it if you need it. 10c20t.

**Comment by palexdev** [comment]
This happened to me too, the memory usage is insane
6MB MP4 video
`gifski --quality 70 --fps 50 --height 720 --width 1280 ...`
Take almost 14GB of RAM, I had to set the quality to 70 and close some programs otherwise command would fail with SIGKILL
