### ISSUE TITLE
Overflow occurs when the number of frames is 256 or more

### ISSUE THREAD

**Issue by kitao** [ImageOptim/gifski#193]
Hello. Thank you for providing very useful library!

Now I'm trying to use the gifski to make animated gif in my game engine.
And when the number of calling `collector.add_frame_rgba` is 256 or more.
'attempt to add with overflow' panic happens at 527th line of lib.fs.

It seems that `consecutive_frame_num` of type u8 in `quantize_frames` is added for each frame process and finally overflow happens. Is there any way to avoid this error? Now I'm using Setting::default() as encoding setting.

When I build the library as release version. This overflow is ignored but I'm not sure this affects the produced gif's quality or not.

Thank you.

**Comment by kornelski** [comment]
Minor detail. Fixed.
