### ISSUE TITLE
1.5.1 tag was marked as `latest release`

### ISSUE THREAD

**Issue by chenrui333** [ImageOptim/gifski#194]
just a reminder that the latest 1.5.1 tag did not get marked as `latest release`, it impedes on the [homebrew formulae update](https://github.com/Homebrew/homebrew-core/pull/85013).

**Comment by kornelski** [comment]
Please don't rely on Microsoft's proprietary features for finding the latest release. Just pick a latest tag from git. The releases page sucks, I keep forgetting to update it, and I resent GitHub for not displaying newer tags unless I manually tag-the-tag via their interface.

**Comment by carlocab** [comment]
Just to clarify: the newest tag is always your latest release, regardless of the what the GitHub UI thinks. Is that correct?

**Comment by kornelski** [comment]
Yes, that's the intention.

**Comment by carlocab** [comment]
That's what I thought, but I thought it would be better to make sure. Thanks for the clarification!
