### ISSUE TITLE
Native application

### ISSUE THREAD

**Issue by Kikobeats** [ImageOptim/gifski#20]
![](https://sindresorhus.com/assets/heic-converter/screenshot2.png)

I'm still fascinated how well works gifski.

Although it's very simple to use it (just two commands), it is limited to dev people.

How difficult could create an app to use it from a GUI?

Something simple and similar to ImageOptim. Probably it could be done using electron.

Inspiration: https://sindresorhus.com/heic-converter

**Comment by kornelski** [comment]
It's possible. It should be easy even. I've created a programmatic API for it, and [cargo-xcode](crates.io/crates/cargo-xcode) helper tool that makes XCode projects for Rust libraries.

It'd be great if @sindresorhus could find some time to make a GUI for it.

**Comment by sindresorhus** [comment]
Yeah, I'll give it a shot next weekend. I could probably reuse most of the code from HEIC Converter (Just need to untangle it from my internal framework).

My plan is to read the video file with `AVFoundation`, and then use `gifski_add_frame_rgba` for each frame.

What settings should be exposed?

Should it support converting multiple videos at once (dragging multiple files)? I don't think most people would do this, so I would say no, as it would also complicate specifying options like width/height.

**Comment by kornelski** [comment]
I've fixed the link and just added the xcode project to the repo, so you can use it as a submodule or such.

For an MVP the default settings are all fine:

```
GifskiSettings {
    pub width: 0,
    pub height: 0,
    pub quality: 100,
    pub once: false,
    pub fast: false,
}
```

Useful quality is in 50-100 range. 

Multiple videos probably don't make sense. You could interpret drop of multiple files as PNG frames to be combined.

Since produced GIFs are large, having ability to limit number of frames would be useful. Ability to convert only a fragment of a video would be ideal.

**Comment by sindresorhus** [comment]
And should I name it `Gifski.app` or something else?

**Comment by kornelski** [comment]
@sindresorhus Yes, you can publish it in the App Store as a free app. Gifski.app is fine.

**Comment by kornelski** [comment]
BTW, I thought you might want to have a progress bar and ability to cancel: bee71e4bdf7cdf77283384a3e5d150372dd96698

**Comment by sindresorhus** [comment]
The app is now out: https://github.com/sindresorhus/gifski-app ✨
