### ISSUE TITLE
How       Panic in local.rs : 287

### ISSUE THREAD

**Issue by wangbang79408854** [ImageOptim/gifski#202]
gifski::Collector::add_frame_png_file::h0a982d7d7a2fd6c8
8   GIF                                       0x00000001004eb39c gifski_add_frame_png_file
9   GIF                                       0x00000001002597f0 __103+[GifGenerateUtils CLIBGifWithUImagePaths:imageSize:withDelay:outputPath:loopCount:quality:Completion:]_block_invoke + [GifGenerateUtils.m : 338] 
10  libdispatch.dylib                   0x0000000181e39914 _dispatch_call_block_and_release
11  libdispatch.dylib                   0x0000000181e3b660 _dispatch_client_callout
12  libdispatch.dylib                   0x0000000181e3e788 _dispatch_queue_override_invoke
13  libdispatch.dylib                   0x0000000181e4cdd0 _dispatch_root_queue_drain
14  libdispatch.dylib                   0x0000000181e4d5f8 _dispatch_worker_thread2
15  libsystem_pthread.dylib             0x00000001f246a0b8 _pthread_wqthread
Thread 13:
0   libsystem_pthread.dylib             0x00000001f2469e8c start_wqthread
Thread 14 name:  c-write
Thread 14 Crashed:
0   libsystem_kernel.dylib              0x00000001b9010964 __pthread_kill
1   libsystem_pthread.dylib             0x00000001f2470378 pthread_kill
2   libsystem_c.dylib                   0x000000018d006f50 abort
3   GIFMakingMastery                    0x000000010052ff78 _ZN3std9panicking11panic_count17LOCAL_PANIC_COUNT7__getit17he3bd836413caf2d6E + [local.rs : 287]

**Comment by kornelski** [comment]
Did it print anything to stderr? Usually a cause of panic is printed before it aborts.
