### ISSUE TITLE
got error with "--features=openmp"

### ISSUE THREAD

**Issue by Mcl15** [ImageOptim/gifski#203]
Hi!
I got error with "cargo build --lib --release --features=openmp --target=aarch64-apple-ios"
What can I do ? Thanks.
  
ERROR INFO:

Compiling imagequant-sys v3.1.1+sys2.17.0
The following warnings were emitted during compilation:

warning: libimagequant.c:23:10: fatal error: 'omp.h' file not found
warning: #include <omp.h>
warning:          ^~~~~~~
warning: 1 error generated.

error: failed to run custom build command for `imagequant-sys v3.1.1+sys2.17.0`

Caused by:
  process didn't exit successfully: `/Users/lyc/Documents/GitWarehouse/gifski/target/release/build/imagequant-sys-2fbeb4140291f5d5/build-script-build` (exit status: 1)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("aarch64-apple-ios")
  HOST = Some("x86_64-apple-darwin")
  CC_aarch64-apple-ios = None
  CC_aarch64_apple_ios = None
  TARGET_CC = None
  CC = None
  CFLAGS_aarch64-apple-ios = None
  CFLAGS_aarch64_apple_ios = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  Detecting iOS SDK path for iphoneos
  running: "xcrun" "--show-sdk-path" "--sdk" "iphoneos"
  exit status: 0
  cargo:include=/Users/lyc/.cargo/registry/src/github.com-1ecc6299db9ec823/imagequant-sys-3.1.1+sys2.17.0
  Detecting iOS SDK path for iphoneos
  running: "clang" "-O3" "-fPIC" "--target=aarch64-apple-ios" "-arch" "arm64" "-miphoneos-version-min=7.0" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk" "-fembed-bitcode" "-Xpreprocessor" "-fopenmp" "-std=c99" "-DNDEBUG=1" "-o" "/Users/lyc/Documents/GitWarehouse/gifski/target/aarch64-apple-ios/release/build/imagequant-sys-8c311c4913acc9e0/out/libimagequant.o" "-c" "libimagequant.c"
  cargo:warning=libimagequant.c:23:10: fatal error: 'omp.h' file not found
  cargo:warning=#include <omp.h>
  cargo:warning=         ^~~~~~~
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr

  error occurred: Command "clang" "-O3" "-fPIC" "--target=aarch64-apple-ios" "-arch" "arm64" "-miphoneos-version-min=7.0" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk" "-fembed-bitcode" "-Xpreprocessor" "-fopenmp" "-std=c99" "-DNDEBUG=1" "-o" "/Users/lyc/Documents/GitWarehouse/gifski/target/aarch64-apple-ios/release/build/imagequant-sys-8c311c4913acc9e0/out/libimagequant.o" "-c" "libimagequant.c" with args "clang" did not execute successfully (status code exit status: 1).

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by kornelski** [comment]
Clang doesn't support OpenMP. You need to use GCC (e.g. install GCC from homebrew and set `CC=gcc-11`). It probably won't work for iOS.

**Comment by kornelski** [comment]
This has been fixed the hard way: https://pngquant.org/rust.html
