### ISSUE TITLE
There are plans to support wasm？

### ISSUE THREAD

**Issue by wangbang79408854** [ImageOptim/gifski#205]

**Comment by kornelski** [comment]
It's already supported.

**Comment by wangbang79408854** [comment]
> It's already supported.


when i  try   to  use   wasm-pack build     , it reports error:

Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
   Compiling imagequant-sys v3.1.1+sys2.17.0
   Compiling gifsicle v1.92.5
error: failed to run custom build command for `imagequant-sys v3.1.1+sys2.17.0`

Caused by:
  process didn't exit successfully: `C:\Users\Administrator\Desktop\cargo-wasm\target\release\build\imagequant-sys-0f9e9fecc1f83a65\build-script-build` (exit code: 1)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("wasm32-unknown-unknown")
  HOST = Some("x86_64-pc-windows-msvc")
  CC_wasm32-unknown-unknown = None
  CC_wasm32_unknown_unknown = None
  TARGET_CC = None
  CC = Some("C:\\Users\\Administrator\\Desktop\\llvm-mingw-20211002-ucrt-x86_64\\bin")
  CFLAGS_wasm32-unknown-unknown = None
  CFLAGS_wasm32_unknown_unknown = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = None
  cargo:include=\\?\C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-b63e9dae659fc205\imagequant-sys-3.1.1+sys2.17.0
  running: "C:\\Users\\Administrator\\Desktop\\llvm-mingw-20211002-ucrt-x86_64\\bin" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-std=c99" "-DNDEBUG=1" "-o" "C:\\Users\\Administrator\\Desktop\\cargo-wasm\\target\\wasm32-unknown-unknown\\release\\build\\imagequant-sys-2dbfe6d7db1a9f95\\out\\libimagequant.o" "-c" "libimagequant.c"

  --- stderr


  error occurred: Command "C:\\Users\\Administrator\\Desktop\\llvm-mingw-20211002-ucrt-x86_64\\bin" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-std=c99" "-DNDEBUG=1" "-o" "C:\\Users\\Administrator\\Desktop\\cargo-wasm\\target\\wasm32-unknown-unknown\\release\\build\\imagequant-sys-2dbfe6d7db1a9f95\\out\\libimagequant.o" "-c" "libimagequant.c" with args "bin" failed to start: Os { code: 5, kind: PermissionDenied, message: "拒绝访问。" }

**Comment by wangbang79408854** [comment]
> It's already supported.
i  
how to  set    PKG_CONFIG_SYSROOT_DIR?  

> It's already supported.
I don’t know how to change the settings. For Android, I will set the cc and sysroot to compile successfully. How to set this wasm packaging environment? I use wasm-pack build to package or the prompt is not found <stdio.h> I think it should be cc and sysroot settings The problem

**Comment by kornelski** [comment]
You need to use emscripten target, which provides stdio.h and alike.

**Comment by wangbang79408854** [comment]
> You need to use emscripten target, which provides stdio.h and alike.
> 
> ```shell
> rustup target add wasm32-unknown-emscripten
> # install emscripten and set up env for emcc, and then
> cargo build --target wasm32-unknown-emscripten --lib
> ```

follow up step。



wangbang@wangbangdeMBP gifski % cargo build --target wasm32-unknown-emscripten --lib
   Compiling imagequant-sys v3.1.1+sys2.17.0
error: linking with `emcc` failed: exit status: 1
  |
  = note: "emcc" "-s" "EXPORTED_FUNCTIONS=[\"_rust_eh_personality\"]" "/Users/wangbang/Desktop/gifski/target/wasm32-unknown-emscripten/debug/deps/imagequant_sys-d430ee6b38434b82.imagequant_sys.a35613c9-cgu.0.rcgu.o" "/Users/wangbang/Desktop/gifski/target/wasm32-unknown-emscripten/debug/deps/imagequant_sys-d430ee6b38434b82.imagequant_sys.a35613c9-cgu.1.rcgu.o" "/Users/wangbang/Desktop/gifski/target/wasm32-unknown-emscripten/debug/deps/imagequant_sys-d430ee6b38434b82.imagequant_sys.a35613c9-cgu.2.rcgu.o" "/Users/wangbang/Desktop/gifski/target/wasm32-unknown-emscripten/debug/deps/imagequant_sys-d430ee6b38434b82.4ko85qtfxh96rry3.rcgu.o" "-L" "/Users/wangbang/Desktop/gifski/target/wasm32-unknown-emscripten/debug/deps" "-L" "/Users/wangbang/Desktop/gifski/target/debug/deps" "-L" "/Users/wangbang/Desktop/gifski/target/wasm32-unknown-emscripten/debug/build/imagequant-sys-4c9e4866b8ce0b7b/out" "-L" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib" "-l" "imagequant" "/Users/wangbang/Desktop/gifski/target/wasm32-unknown-emscripten/debug/deps/librgb-e37987976aa874e8.rlib" "/Users/wangbang/Desktop/gifski/target/wasm32-unknown-emscripten/debug/deps/libbytemuck-e508ec82a1bd39f4.rlib" "/Users/wangbang/Desktop/gifski/target/wasm32-unknown-emscripten/debug/deps/libbitflags-173ce9e7837a329f.rlib" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib/libstd-3ea5e5e81f42cb18.rlib" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib/libpanic_unwind-292787a6a78a8192.rlib" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib/libstd_detect-9d901892c54fdcdc.rlib" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib/librustc_demangle-7f2eb1f74eabebea.rlib" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib/libhashbrown-d2fc568ef2bdaef9.rlib" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib/librustc_std_workspace_alloc-4f216f648113d375.rlib" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib/libunwind-f0eb3f7383df10d8.rlib" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib/libcfg_if-141c9fbf0135ce9b.rlib" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib/liblibc-ed531e023e9b0d0d.rlib" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib/liballoc-5ec9f06ec9ad2d82.rlib" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib/librustc_std_workspace_core-4b6b0eff424d3a8f.rlib" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib/libcore-77c7b92aba6c8c30.rlib" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib/libcompiler_builtins-f5e2360d5827b414.rlib" "-l" "c" "-s" "DISABLE_EXCEPTION_CATCHING=0" "-L" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib" "-L" "/Users/wangbang/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-emscripten/lib/self-contained" "-o" "/Users/wangbang/Desktop/gifski/target/wasm32-unknown-emscripten/debug/deps/imagequant_sys-d430ee6b38434b82.wasm" "-O2" "--memory-init-file" "0" "-g0" "-s" "DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[]" "-s" "ERROR_ON_UNDEFINED_SYMBOLS=1" "-s" "ASSERTIONS=1" "-s" "ABORTING_MALLOC=0" "-Wl,--fatal-warnings"
  = note: error: undefined symbol: __gxx_personality_v0 (referenced by top-level compiled C/C++ code)
          warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
          warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
          warning: ___gxx_personality_v0 may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
          error: undefined symbol: main (referenced by top-level compiled C/C++ code)
          warning: _main may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
          warning: To build in STANDALONE_WASM mode without a main(), use emcc --no-entry
          Error: Aborting compilation due to previous errors
          emcc: error: '/Users/wangbang/emsdk/emsdk/node/14.15.5_64bit/bin/node /Users/wangbang/emsdk/emsdk/upstream/emscripten/src/compiler.js /var/folders/lj/qz8t6q113lsg5l39mh1rctrc0000gn/T/tmpvlzw32dv.txt' failed (returned 1)
          

error: could not compile `imagequant-sys` due to previous error

**Comment by wangbang79408854** [comment]
https://github.com/rust-lang/rust/issues/85821     this。reslove my error

**Comment by kornelski** [comment]
Great.

**Comment by wangbang79408854** [comment]
Do you have the glue js for the wasm project? I found that the wasm file packaged in the project is difficult to use

**Comment by kornelski** [comment]
No, I don't. You'll have to use the [public interface in Rust](https://docs.rs/gifski/latest/gifski/), and then export (perhaps with wasm-bindgen) your own entry point.

**Comment by wangbang79408854** [comment]
wasm-bindge  is use  wasm32-unknown-unknown?  but  gifski  is only  use wasm32-unknown-emscripten

**Comment by kornelski** [comment]
Ooof, indeed. You'll need to manually write the wrapper using `#[no_mangle] extern fn`. I haven't done it this way, so I can't recommend specifics.

**Comment by wangbang79408854** [comment]
I have given up using wasm, on the server，How to start multithreading, currently only two CPUs are used

**Comment by jamsinclair** [comment]
If anyone stumbles upon this issue via a search engine or llm, I've hacked together a wasm port with an easy JavaScript interface that should be easy to get started with – https://github.com/jamsinclair/gifski-wasm.
