### ISSUE TITLE
test program with c bindings only uses first two frames

### ISSUE THREAD

**Issue by scottjg** [ImageOptim/gifski#206]
i am trying to build a screen recording app using libgifski to generate gifs, but the generated gifs only ever seem to contain the first two frames of video. i've created a simplified reproducible test case at https://github.com/scottjg/giftest

I am running macos 12.01 on an m1 mac.
```
scottjg@scottjgs-Air giftest % clang --version
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: arm64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
scottjg@scottjgs-Air giftest % rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)
```

if you checkout that example repo, you can just run `make && ./giftest` to see the issue in the generated `file.gif`. the simplified test code looks like this:

```c
#include <stdio.h>
#include <gifski.h>

int main(int argc, char *argv[])
{
    printf("Hello, world!\n");

    gifski *g = gifski_new(&(GifskiSettings){});
    gifski_set_file_output(g, "file.gif");

    for(int i=0; i < 25; i++) {
        char filename[256];
        sprintf(filename, "frame%d.png", i);
        int res = gifski_add_frame_png_file(g, i, filename, i / 10.0);
        if (res != GIFSKI_OK) break;
    }
    int res = gifski_finish(g);
    if (res != GIFSKI_OK) return res;

    return 0;
} 
```

one odd thing i noticed is if i use the `gifski` binary, it works... so it might be a problem specific to the c bindings (or, of course, some problem with my usage).

**Comment by scottjg** [comment]
code seems to behave the same on x86_64 linux:
```
root@98ecaa3528a0:/giftest# rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)
root@98ecaa3528a0:/giftest# gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by kornelski** [comment]
This is because you've set `quality` setting to `0`, and it makes gifski think it's not important to keep "similar" frames.

**Comment by scottjg** [comment]
thanks so much! changing the quailty setting fixed it. it might be worth updating the example code in gifski.h to include the quality param, that was where i had cribbed this from.

**Comment by kornelski** [comment]
Thanks
