### ISSUE TITLE
result error with alpha gif

### ISSUE THREAD

**Issue by ZhouXiaolin** [ImageOptim/gifski#209]
when i render a gif with alpha, the result error like 
[image](https://pichuang.oss-cn-beijing.aliyuncs.com/img/202201141648488.png)

this is my gif 
https://drive.google.com/file/d/1XdetcTQEgj-lUb6cd5BFVdFBkxGpxXqA/view?usp=sharing

**Comment by kornelski** [comment]
Do you mean it gets a brown background? Can you provide the frames you've used as an input?

**Comment by ZhouXiaolin** [comment]
> Do you mean it gets a brown background? Can you provide the frames you've used as an input?

https://drive.google.com/file/d/1XdetcTQEgj-lUb6cd5BFVdFBkxGpxXqA/view?usp=sharing   , this is input gif, the output background is brown

**Comment by kornelski** [comment]
gifski doesn't support gifs as input. How did you make it take a gif?

**Comment by ZhouXiaolin** [comment]
> gifski doesn't support gifs as input. How did you make it take a gif?

ffmpeg decode gif to rgba, then i use gifski's add_frame_rgba function,

**Comment by kornelski** [comment]
I can't reproduce this, but I've fixed a couple of bugs that could have been related.
