### ISSUE TITLE
Gifski v1.6.3 | There is a big problem with synthesizing pictures of transparent channels

### ISSUE THREAD

**Issue by Jdb156158** [ImageOptim/gifski#210]
[source material.zip](https://github.com/ImageOptim/gifski/files/7896353/source.material.zip)

Boss, after I use gifski to synthesize the above pictures to generate GIF, the color values of GIF pictures are disordered. I test that it will appear only when the material background is transparent in a large area.

Operation steps:
gifski --repeat 1 --fps 1 -o anim. gif IMG*. png

Gifski version:
v1.6.3

Thank you very much and look forward to your solution

**Comment by kornelski** [comment]
Fixed in 1.6.4
