### ISSUE TITLE
Strip?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageOptim/gifski#211]
Hi @kornelski .

Maybe `strip` elf-files?
[gifski_1.6.4-chimaera_amd64.deb.gz](https://github.com/ImageOptim/gifski/files/7898338/gifski_1.6.4-chimaera_amd64.deb.gz)

```sh
$ ls -s gifski_1.6.4-chimaera_amd64.deb 
7612 gifski_1.6.4-chimaera_amd64.deb
```

**Comment by kornelski** [comment]
I think they are stripped

**Comment by zvezdochiot** [comment]
Hi @kornelski .

Not.
```sh
$ ls -1s
23192 gifski_1.6.4_amd64.deb
 7612 gifski_1.6.4-chimaera_amd64.deb
```

**Comment by kornelski** [comment]
How did you build it? What strip command did you apply?

**Comment by zvezdochiot** [comment]
Hi @kornelski .

I use https://github.com/BASH-Auto-Tools/bash-deb-build for unpack/pack package.

For strip:
```sh
$ strip ./CONTENTS/usr/bin/gifski
$ strip ./CONTENTS/usr/lib/libgifski.so
```

**Comment by kornelski** [comment]
That's just basic `strip`, which I use too. I assume the file size difference exists only because you've built it without video decoding support.

**Comment by zvezdochiot** [comment]
Hi @kornelski .

Not. I didn't compile anything. I took your package. Unpacked it. Produced `strip`. Checked the dependencies. Edited the config. Packed a package.

**Comment by kornelski** [comment]
You're right. Indeed I had a bug in cargo-deb that caused it to skip stripping. Thank you for being patient with me :)
