### ISSUE TITLE
Looping forward and backward

### ISSUE THREAD

**Issue by stla** [ImageOptim/gifski#212]
Hello,

  This is a feature request. It would be nice to have an option to produce a gif which loops forward and backward. With ImageMagick we can do that with the `duplicate` option, by running a command like:

`magick convert -delay 1x9 -duplicate 1,-2-1 pics*.png output.gif`

![](https://github.com/stla/PyVistaMiscellanous/raw/main/C8surface_metamorphosis.gif)

Cheers.

**Comment by kornelski** [comment]
I do not want to extend this tool into being a video editor. You can achieve this effect by duplicating frames yourself.

**Comment by stla** [comment]
Ok, I understand. Anyway I'm using **gifski** via R, and then I wrote my own bash command **gifski** with a R script, and it has a forward-backward option. I've just written a [blog post](https://laustep.github.io/stlahblog/posts/gifskiBash.html) about it, in case someone is interested.
