### ISSUE TITLE
Gifski v1.6.4 | The image of the synthetic transparent channel will have a lot of jagged edges

### ISSUE THREAD

**Issue by Jdb156158** [ImageOptim/gifski#215]
[source material.zip](https://github.com/ImageOptim/gifski/files/8031754/source.material.zip)

Big guy, in the latest version of Gifski 1.6.4, there will be a lot of jagged edges in the GIF generated from the picture with the transparent channel. Is there any way to solve it?

Operation steps:
gifski --repeat 1 --fps 1 -o anim. gif IMG*. png

Gifski version:
v1.6.4

Thank you very much and look forward to your solution

**Comment by kornelski** [comment]
This is unavoidable. The GIF format doesn't support alpha transparency.

**Comment by Jdb156158** [comment]
![anim](https://user-images.githubusercontent.com/18107143/153330421-0b533d32-dc18-4814-bff6-547951320a5a.gif)
但是这种锯齿毛边有点太夸张了，是否能优化一下，锯齿毛边不那么明显？非常感谢，希望您有解决方案。

But this kind of serrated burr is a bit too exaggerated. Can it be optimized so that the serrated burr is not so obvious?
Thank you very much and look forward to your solution
