### ISSUE TITLE
Option to disable alpha dithering

### ISSUE THREAD

**Issue by andylizi** [ImageOptim/gifski#218]
| With dithering | Without dithering |
| --- | --- |
| | |
| <img src="https://user-images.githubusercontent.com/12008103/153713384-788b3009-58a5-4fd0-be6f-dbb7259d2df5.gif" width="300"> | <img src="https://user-images.githubusercontent.com/12008103/153713385-1f746ec8-90fa-4705-994f-eb694ed8ea35.gif" width="300"> |

<sub> (Image attribution: <a href="https://icons8.com/animated-icons/color/bell">icons8.com</a>) </sub>

On a darker background it's even more distinct:

![dark](https://user-images.githubusercontent.com/12008103/153713661-a3a25513-b4c8-48c6-b54e-1e03e05887f6.png)

Similar to #215, this kind of jagged effect is most prominent on low-res GIFs. The right image is produced by changing `resized_binary_alpha` to:

```rust
// Make transparency binary
image.pixels_mut().filter(|px| px.a < 255).for_each(|px| { px.a = if px.a < 128 { 0 } else { 255 }; });
````

The edges are still uncomfortably sharp ⁠— that's indeed unavoidable, but it's much, much better than the dithered version.

**Comment by kornelski** [comment]
I see what you mean. I'll try to improve it.

**Comment by kornelski** [comment]
Should be fine now.

**Comment by Jdb156158** [comment]
#

> 现在应该好了。

这个问题，我使用了最新的1.7.0版本来测试：#215 中的素材，发现并没有好，还是有很多的锯齿。边缘锯齿问题还是存在，大佬，你可以用那些素材做一个测试看看是否还是那样。 @andylizi
