### ISSUE TITLE
Using from npm package

### ISSUE THREAD

**Issue by usman074** [ImageOptim/gifski#219]
I am running an open-source project which depends upon gifski, and for that I install it using this command
"brew install gifski"
But I dont want to install it separately, what I want is when user runs the application it resolve it's dependencies automatically. What I found is an npm package for gifski here
https://www.npmjs.com/package/gifski
But I dont know how I should use this package in node to resolve my issue. Kindly guide me to use it so that I dont need to use a brew to install gifski separately.

**Comment by kornelski** [comment]
The package has no JS interface. It's only the same command-line executable you get from brew. You need to launch the binary using child_process.spawn(), the same as the brew one.

**Comment by usman074** [comment]
This is the same information that you provided with the npm package, Could you please provide a sample code how to launch binary in node JS.

**Comment by ShayBox** [comment]
[This page](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) documents Child process's spawn options and has examples
