### ISSUE TITLE
Can you add `input image` from pipe line?

### ISSUE THREAD

**Issue by leeonix** [ImageOptim/gifski#223]
I using Gifski generate gif, it's so good.
before using Gifski I use this:

get-gif.bat:
ffmpeg -ss %2 -t %3 -i %1 -vf "fps=10,scale=-1:360:flags=spline" -c:v pam -f image2pipe - | magick -delay 10 - -loop 0 -layers optimize %1.gif

ffmpeg generate image files to pipe line. ImageMagick read pipe line create a gif.

Can you add input image from pipe line?

**Comment by kornelski** [comment]
I can't find docs for image2pipe format. Is it merely files concatenated together?

Anyway, gifski can take a video as an argument and resize it.

**Comment by scribblemaniac** [comment]
> I can't find docs for image2pipe format. Is it merely files concatenated together?

From experience, yes. The format of the individual images is specified as the codec (ex. `-c:v png`).

I agree though that I don't see much use for this feature. Worst case scenario (ex. you have to apply some custom filtering to a video before converting) you just have to write your files to the disk as an image sequence before calling gifski. If a png image sequence takes up too much space, then the output gif will likely take up too much space as well.

**Comment by kornelski** [comment]
Good point about the size. A pipe would be elegant, but reasonably sized animations can be done without it.

**Comment by kornelski** [comment]
This is now supported via y4m streams
