### ISSUE TITLE
“error: The file has no video tracks”

### ISSUE THREAD

**Issue by Dizzota** [ImageOptim/gifski#225]
recently, i updated gifski from v1.6.4 to v1.7.0 (using this GitHub repository) with _video support_, which was definitely difficult to set up, but i managed to get it to work in gifski v1.6.4.

![notepad++_KRseSguTo8](https://user-images.githubusercontent.com/49292820/157370384-159a75e1-967c-4cd7-904d-81377df62c07.png)

![notepad++_JhjTJjtM4g](https://user-images.githubusercontent.com/49292820/157370391-1c5da7b5-c08c-49dc-a96f-ab5b56edfd5c.png)

and now, ever since i updated to v1.7.0, video support no longer works and throws this mysterious error instead?

![cmd_DIi0K3cCsL](https://user-images.githubusercontent.com/49292820/157370482-2f0b888b-e62f-40c1-8d50-d95bbd4414e0.png)

i tried making research on this “no video tracks” error, but had no luck getting anything helpful.

did something change about video support in this repo's latest version? i compiled gifski v1.7.0 with `cargo build --release --features=video`.

**Comment by kornelski** [comment]
It means ffmpeg doesn't support this MP4 file. It may be encoded in some complex way that the decoder doesn't understand how to use.

**Comment by Dizzota** [comment]
maybe, but even if that was the case, ffmpeg/gifski (v1.6.4) was able to encode the mp4 into a gif anyway, but a later version suddenly can't.

it doesn't really make sense to me, but considering how hard it is to get gifski _working with video support_...maybe this isn't surprising.

is there a way to compile an older version of gifski by any chance?

**Comment by andylizi** [comment]
Maybe it would help if you can run `ffprobe` on the video file and check the output

**Comment by Dizzota** [comment]
> Can you reproduce the issue with different versions of gifski, but the same version of ffmpeg?

i'm not exactly sure what you mean, the ffmpeg i have in PATH is “`ffmpeg version n4.4.1`,” which is apparently what works for gifski according to the documentation.

however, it seems like the dependency named `ffmpeg-sys-next` was updated to “v5.0.1” in gifski v1.6.6. that might be related to why it's not properly decoding video files.

here are the results for when i downgraded to [gifski v1.6.6](https://crates.io/crates/gifski/1.6.6) and then [gifski v1.6.4](https://crates.io/crates/gifski/1.6.4), using `cargo install gifski --version 1.6.6 --features=video` and `cargo install gifski --version 1.6.4 --features=video`:

[gifski v1.6.6](https://crates.io/crates/gifski/1.6.6) (fail)

![cmd_dMIee16ZK2](https://user-images.githubusercontent.com/49292820/157580936-dca6060b-71fd-4a3c-b5f4-f4aad45f3add.png)

[gifski v1.6.4](https://crates.io/crates/gifski/1.6.4) (success)

![MjENSGAioy](https://user-images.githubusercontent.com/49292820/157580972-7e10a5ff-8fba-415a-8e1d-ce8a1a7c41cb.png)

![cmd_OjzM7k8gVn](https://user-images.githubusercontent.com/49292820/157580982-cd10f9e0-92c7-4fbc-a7c6-76ed9d02e4df.png)

**Comment by Dizzota** [comment]
> Maybe it would help if you can run `ffprobe` on the video file and check the output

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\User\Downloads\Video\mewhen.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
  Duration: 00:00:04.81, start: 0.000000, bitrate: 238 kb/s
  Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 404x360 [SAR 1:1 DAR 101:90], 138 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
```

**Comment by Dizzota** [comment]
> Can you reproduce the issue with different versions of gifski, but the same version of ffmpeg?

_WAIT..._ @kornelski

i downgraded `ffmpeg-next` back to v4.4.0 like in gifski v1.6.4, and video support suddenly works again in gifski v1.7.0!

![WrbOT4ETIf](https://user-images.githubusercontent.com/49292820/157586364-7b8daa2b-0708-4dd3-be3e-9bcc56b87dfa.png)

it seems like the problem is that gifski doesn't know how to decode using ffmpeg v5.x.

this warning might be a hint:

```
warning: use of deprecated associated function `ffmpeg_next::decoder::Video::decode`: Underlying API avcodec_decode_video2 has been deprecated since FFmpeg 3.1; consider switching to send_packet() and receive_frame()
   --> src\bin\ffmpeg_source.rs:106:35
    |
106 |             let decoded = decoder.decode(&packet, &mut vid_frame)?;
    |                                   ^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default
```

**Comment by kornelski** [comment]
Yeah, that's probably it. Sad "deprecated" here means broken.

**Comment by Dizzota** [comment]
you should either implement ffmpeg v5.x support or edit Cargo.toml to use ffmpeg-next 4.x for video support only, since anything higher than 4.x breaks the decoder.

**Comment by kornelski** [comment]
Yeah
