### ISSUE TITLE
cargo build gifski   use lib error

### ISSUE THREAD

**Issue by wangbang79408854** [ImageOptim/gifski#227]
when i want to add windows project

lib
 -gifski.lib

CMAKEList 

cmake_minimum_required(VERSION 3.15)
set(PROJECT_NAME "gifski_plugin")
project(${PROJECT_NAME} LANGUAGES CXX)

# This value is used when generating builds using this plugin, so it must
# not be changed
set(PLUGIN_NAME "gifski_plugin_plugin")

link_directories("${PROJECT_SOURCE_DIR}/lib/")

add_library(${PLUGIN_NAME} SHARED
  "gifski_plugin.cpp"
)
apply_standard_settings(${PLUGIN_NAME})
set_target_properties(${PLUGIN_NAME} PROPERTIES
  CXX_VISIBILITY_PRESET hidden)
target_compile_definitions(${PLUGIN_NAME} PRIVATE FLUTTER_PLUGIN_IMPL)
target_include_directories(${PLUGIN_NAME} INTERFACE
  "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(${PLUGIN_NAME} PRIVATE flutter flutter_wrapper_plugin "gifski")

# List of absolute paths to libraries that should be bundled with the plugin
set(gifski_plugin_bundled_libraries
  "${PROJECT_SOURCE_DIR}/bin/"
  PARENT_SCOPE
)

run reports;

gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_WSAStartup，函数 _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h2c8920d936a7f5baE 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_WSACleanup，函数 _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h2c8920d936a7f5baE 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_freeaddrinfo，函数 _ZN4core3ptr158drop_in_place$LT$core..iter..adapters..map..Map$LT$std..sys_common..net..LookupHost$C$std..net..addr..resolve_socket_addr..$u7b$$u7b$closure$u7d$$u7d$$GT$$GT$17h5088f0ad79811dbaE 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_closesocket，函数 _ZN4core3ptr51drop_in_place$LT$std..sys..windows..net..Socket$GT$17h53d270c27363f406E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_BCryptGenRandom，函数 _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h5d9e7fddda86c91eE 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(getrandom-300f00d6e6980c05.getrandom.4667f489-cgu.5.rcgu.o) : error LNK2001: 无法解析的外部符号 __imp_BCryptGenRandom [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_GetUserProfileDirectoryW，函数 _ZN3std3env8home_dir17h1070ffe55669b4a3E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_shutdown，函数 _ZN3std3net3tcp9TcpStream8shutdown17h3b79873b6012c83cE 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_WSAGetLastError，函数 _ZN3std3net3tcp9TcpStream8shutdown17h3b79873b6012c83cE 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_setsockopt，函数 _ZN3std3net3tcp9TcpStream16set_read_timeout17h308d8fb2820b1cb7E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_getsockopt，函数 _ZN3std3net3tcp9TcpStream12read_timeout17ha9aee434e3882bd5E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_recv，函数 _ZN3std3net3tcp9TcpStream4peek17h74de5805ceff1e19E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_WSARecv，函数 _ZN58_$LT$std..net..tcp..TcpStream$u20$as$u20$std..io..Read$GT$13read_vectored17h8888cb4e2f996ed9E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_WSASend，函数 _ZN59_$LT$std..net..tcp..TcpStream$u20$as$u20$std..io..Write$GT$14write_vectored17he5046b85a0107089E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_send，函数 _ZN63_$LT$$RF$std..net..tcp..TcpStream$u20$as$u20$std..io..Write$GT$5write17hd072be4f5a001207E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_accept，函数 _ZN3std3net3tcp11TcpListener6accept17h8d77fe9bc846e44fE 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_ioctlsocket，函数 _ZN3std3net3tcp11TcpListener15set_nonblocking17h3c6d88cf7619bf44E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_getpeername，函数 _ZN3std3net3udp9UdpSocket9peer_addr17h547e4062172e4ce7E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_WSASocketW，函数 _ZN3std3sys7windows3net6Socket3new17h265af10de9dc1b8dE 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_connect，函数 _ZN3std3sys7windows3net6Socket15connect_timeout17hade182b834a5cef5E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_select，函数 _ZN3std3sys7windows3net6Socket15connect_timeout17hade182b834a5cef5E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_WSADuplicateSocketW，函数 _ZN3std3sys7windows3net6Socket9duplicate17hb66d112323b43c30E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_recvfrom，函数 _ZN3std3sys7windows3net6Socket20recv_from_with_flags17h3afc93fa9af514e9E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_getaddrinfo，函数 _ZN104_$LT$std..sys_common..net..LookupHost$u20$as$u20$core..convert..TryFrom$LT$$LP$$RF$str$C$u16$RP$$GT$$GT$8try_from17he6bc53e6a5ab918dE 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_getsockname，函数 _ZN68_$LT$std..sys_common..net..TcpStream$u20$as$u20$core..fmt..Debug$GT$3fmt17h251ab409b6e440fdE 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_bind，函数 _ZN3std10sys_common3net11TcpListener4bind17h782d2474a182925aE 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_listen，函数 _ZN3std10sys_common3net11TcpListener4bind17h782d2474a182925aE 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
gifski.lib(std-2fd39a6aded97dd9.std.5a5a124a-cgu.0.rcgu.o) : error LNK2019: 无法解析的外部符号 __imp_sendto，函数 _ZN3std10sys_common3net9UdpSocket7send_to17h4cbf56aee3cc7445E 中引用了该符号 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\Debug\gifski_plugin_plugin.dll : fatal error LNK1120: 27 个无法解析的外部命令 [C:\Users\Administrator\Desktop\gifski_plugin\example\build\windows\plugins\gifski_plugin\gifski_plugin_plugin.vcxproj]
Exception: Build process failed.

**Comment by dnjulek** [comment]
I had the same issue when trying to use gifski as a lib, here a list of extra libs that need to be linked in the project:
https://github.com/dnjulek/vapoursynth-gifski/blob/7736bfbe3c3a7a2cf81d30da2642427b4074753e/build.zig#L31-L34
