### ISSUE TITLE
gifs glitch out if the first few frames are the same.

### ISSUE THREAD

**Issue by xDoomsdayz** [ImageOptim/gifski#245]
Hi, I have been doing some tests on the gifs and noticed an issue with the encoder. It removes duplicate images and extends the duration to the wrong frame.

![1](https://user-images.githubusercontent.com/29497392/171485739-b7cb06a4-23a0-40d2-897e-3c5dd45e9a68.gif)
![image](https://user-images.githubusercontent.com/29497392/171486193-fd925336-40ab-446a-9ee8-6a5055ad629c.png)
![image](https://user-images.githubusercontent.com/29497392/171486541-eda4d1c9-5124-48b0-af93-226226749df4.png)

I did another test with all the different frames and it's working fine.

![0](https://user-images.githubusercontent.com/29497392/171487253-2cee3b2b-fc76-4220-b54c-c0c9a1acf98b.gif)
![image](https://user-images.githubusercontent.com/29497392/171487303-26dbb3a5-d16d-41a1-bfdb-1264521ae445.png)
![image](https://user-images.githubusercontent.com/29497392/171487532-42069b7e-7d81-413c-b1b0-6c90036a1112.png)

**Comment by jalagar** [comment]
Following this thread!

**Comment by kornelski** [comment]
Can you attach individual png frames so that I can test encoding myself?

**Comment by xDoomsdayz** [comment]
[1.zip](https://github.com/ImageOptim/gifski/files/8845961/1.zip)
heres the zipfile
