### ISSUE TITLE
Installing gifski in Colab R Kernel

### ISSUE THREAD

**Issue by AlejandroDGR** [ImageOptim/gifski#247]
As I've stated in this [stackoverflow question](https://stackoverflow.com/questions/72545526/installing-gifski-in-colab-fails/72546144#72546144), I have problems installing the `gifski` package in Colab R Kernel.
Until this morning, I was using this code:
```
system("apt-get install -y libffmpeg-dev libpngquant-dev")
system("apt-get install rust")
install.packages("gifski")
library(gifski)
```
And it worked with no problems. However, some hours ago, the code stopped working and the following error arises:
```
Warning message in install.packages("gifski"):
“installation of package ‘gifski’ had non-zero exit status”
Error in library(gifski): there is no package called ‘gifski’
Traceback:

1. library(gifski)
```
Any idea why this is happening?

**Comment by kornelski** [comment]
Sorry, this is specific to R and/or Collab, and I don't know these.

**Comment by AlejandroDGR** [comment]
No problem. Thank you.

I leave here the solution that I get by trial and error. I guess the problem was not related to `gifski` itself, but with the `sf` package, whose installation isn't straightforward in Collab too.

You must install `gifski` before `sf`, not the other way around:
```
system("apt-get install -y libffmpeg-dev libpngquant-dev")
system("apt-get install rustc")
install.packages("gifski")
library(gifski)

system("apt-get -y update")
system("apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev")
install.packages("sf")
library(sf)
```
