### ISSUE TITLE
Change the `quality` option to be a `Double`

### ISSUE THREAD

**Issue by sindresorhus** [ImageOptim/gifski#25]
https://docs.rs/gifski/0.7.4/gifski/c_api/struct.GifskiSettings.html#structfield.quality

It's more natural from a developer perspective to use a float to describe a range.

**Comment by kornelski** [comment]
Do you mean range 0..1?

**Comment by sindresorhus** [comment]
Yes, I should have been clearer, a Double between 0 and 1.

**Comment by sindresorhus** [comment]
Would you accept a PR for this?

**Comment by sindresorhus** [comment]
Any reason `width` and `height` are using `u32` instead of just `usize`? I can't imagine performance is a concern here.

**Comment by kornelski** [comment]
`float quality and `usize` dimensions would be slightly more elegant, but I'm not convinced that it's important enough to change — GIF can't have dimensions that large, and quality in pngquant is not sensitive enough to need more than a few levels.
