### ISSUE TITLE
Windows asset file name typo in 1.7.2 release

### ISSUE THREAD

**Issue by tech189** [ImageOptim/gifski#258]
The latest release with the experimental Windows GUI has **1.7.1** (instead of .2) in the .msi filename: https://github.com/ImageOptim/gifski/releases/download/1.7.2/gifski-win_1.7.1_x64_en-US.msi

It's a minor thing, but I would like to add GifSki GUI to [the Scoop package manager](https://scoop.sh) and it would require consistent file name versions with the release's version number so that it can get the latest version automatically. Thanks!

**Comment by kornelski** [comment]
That won't be easy, because the GUI is a separate application, built and updated separately from the main project.
