### ISSUE TITLE
very slowly  use in  gif encoder

### ISSUE THREAD

**Issue by ftanx** [ImageOptim/gifski#260]
1080p  4fps

**Comment by kornelski** [comment]
Yes, this is expected.  

GIF was never designed to handle such resolutions. It was meant for tiny icons, not full screen video. When GIF was designed 320x200 screen was a high resolution, and HD has 32 more pixels than this. The GIF format is awfully inefficient and unsuitable for this, and gifski has to a lot of work to compress it and make it look good at that size.

**Comment by ftanx** [comment]
Thank you!
