### ISSUE TITLE
gifski-command npm package - Node.js module for gifski GIF encoder CLI

### ISSUE THREAD

**Issue by pichillilorenzo** [ImageOptim/gifski#262]
Hello to everyone!

I'm writing here just to announce that I have created a Node.js module wrapper for the gifski CLI 🎉.

NPM Package: https://www.npmjs.com/package/gifski-command
GitHub repo: https://github.com/pichillilorenzo/gifski-command

It uses your [gifski](https://www.npmjs.com/package/gifski) npm package under the hood to download the [gif.ski](https://gif.ski/) executables and `child_process.spawn` to spawn the process.

Here is a simple code example:
```javascript
import * as path from 'path';
import {GifskiCommand} from 'gifski-command';
// or
const path = require('path');
const {GifskiCommand} = require('gifski-command');

const command = new GifskiCommand({
  output: path.join(__dirname, 'test', 'video.gif'),
  frames: [ path.join(__dirname, 'test', 'video.mp4.frame*.png') ],
  quality: 100
});
command.on('progress', progress => {
  console.log(progress);
});
const result = await command.run();
```

The API Reference is available at [https://pichillilorenzo.github.io/gifski-command/](https://pichillilorenzo.github.io/gifski-command/).

**Comment by kornelski** [comment]
Thanks!
