### ISSUE TITLE
Latest release on crates.io missing features?

### ISSUE THREAD

**Issue by Heliozoa** [ImageOptim/gifski#267]
Hi,
Thanks for your work on gifski.

When I try to run (as instructed by an error message)
```
cargo install gifski --features=video
```
I get
```
❯ cargo install gifski --features=video
    Updating crates.io index
  Installing gifski v1.7.2
error: failed to compile `gifski v1.7.2`, intermediate artifacts can be found at `/tmp/cargo-installY0dy60`

Caused by:
  none of the selected packages contains these features: video
```
Looking at https://docs.rs/crate/gifski/1.7.2/features I can see that it indeed doesn't have the video feature, whereas https://docs.rs/crate/gifski/1.7.0/features does. I don't really understand why, since the Cargo.toml here and in the source included in the latest release has the video feature listed... Could something have gone wrong when the latest release was published, or am I just missing something here?

**Comment by kornelski** [comment]
It seems that both @meh and @zmwangx have stopped making releases for bindings to ffmpeg. Existing releases are too old and busted, so video support in gifski has bitrotten.

**Comment by meh** [comment]
What's busted? Can do new release.

**Comment by kornelski** [comment]
The latest release on crates-io is two years old.

**Comment by kornelski** [comment]
Now it works with the latest ffmpeg-next.
