### ISSUE TITLE
coredump when create thread quantize_frames

### ISSUE THREAD

**Issue by NOTRp** [ImageOptim/gifski#269]
#0  0x00007f3c36b8c283 in __rust_probestack () from ./lib/xxxxx.so.1
#1  0x00007f3c36a9b7e4 in gifski::Writer::quantize_frames::h7faa5cca69393468 () from ./lib/xxxxxx.so.1
#2  0x00007f3c36bbde17 in std::sys_common::backtrace::__rust_begin_short_backtrace::h2d821a98434e5142 ()
   from ./lib/xxxxxx.so.1
#3  0x00007f3c36a9f9bc in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h48af701579656b0c ()
   from ./lib/xxxxxxx.so.1
#4  0x00007f3c36b4b6b3 in call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global> ()
    at library/alloc/src/boxed.rs:1935
#5  call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global> ()
    at library/alloc/src/boxed.rs:1935
#6  std::sys::unix::thread::Thread::new::thread_start::ha6436304a1170bba () at library/std/src/sys/unix/thread.rs:108
#7  0x00007f3c44826ea5 in start_thread () from /lib64/libpthread.so.0
#8  0x00007f3c4390f9fd in clone () from /lib64/libc.so.6

**Comment by kornelski** [comment]
Where is that xxxxxxx.so.1 coming from?
