### ISSUE TITLE
Build from source on mac with all features.

### ISSUE THREAD

**Issue by melMass** [ImageOptim/gifski#27]
Hello,

Here is how I built gifski from source:

```zsh
# clone the repo
git clone https://github.com/ImageOptim/gifski
```
On mac  gcc is a symlink to Clang, but the old apple version doesn't have built-in support for OpenMP [see here](http://blog.llvm.org/2015/05/openmp-support_22.html) so:

```zsh
brew install gcc
export CC="/usr/local/bin/gcc-7"
cargo update
cargo build --release --features=openmp
```

But is fails when adding ffmpeg support:

```zsh
cargo build --release --features=video,openmp --verbose
```
The output (shortened to essential):

It rightly links against brew libs (ffmpeg installed from HEAD):
> rustc --crate-name ffmpeg   --crate-type lib-L native=/usr/local/Cellar/ffmpeg/HEAD-7414d0b/lib

*The errors*:

> pixel.rs : 696 Pixel::VDA_VLD     => AV_PIX_FMT_VDA_VLD,
    |                                   ^^^^^^^^^^^^^^^^^^ did you mean `AV_PIX_FMT_VAAPI_VLD`?
                      740 Pixel::VDA => AV_PIX_FMT_VDA,
    |                           ^^^^^^^^^^^^^^ did you mean `AV_PIX_FMT_CUDA`?
                      803  Pixel::XVMC   => AV_PIX_FMT_XVMC,
    |             ^^^^^^^^^^^ variant not found in `util::format::pixel::Pixel`

**Comment by kornelski** [comment]
Yeah, the ffmpeg crate is a broken mess:

https://github.com/meh/rust-ffmpeg/pull/97
https://github.com/meh/rust-ffmpeg/issues/90

I plan to migrate video support go gstreamer (it has excellent Rust support), but haven't had time to do it yet.

**Comment by melMass** [comment]
Oh I see... I guess meh abandoned the project. I've never tried binding other language to rust.
The gstreamer one does seem to be well maintained.
Too much of a newbie in Rust to be able to PR anything to this project.

I've made a simple binary wrapper in PyQt, I'll upload the repo this week if anyone is interested.

**Comment by kornelski** [comment]
I've switched to less-broken ffmpeg crate. It should work now.
