### ISSUE TITLE
Any way or math formula to get an estimated filesize please ? 

### ISSUE THREAD

**Issue by jalba69** [ImageOptim/gifski#28]
Hello kornelski,

After spending lot of time on trying to get the video support on windows i gave up on this and used my poor powershell knowledge to make me a small script to automate all this while using it inside [Staxrip](https://github.com/stax76/staxrip).

![anim](https://user-images.githubusercontent.com/15131985/36875509-85bb62b8-1db0-11e8-9425-3e8ce2e5a7a6.gif)

I select/trim the section of the video i want, add filters or some text or whatever is needed then call the powershell script from a custom menu i added into Staxrip, set my parameters and it will feed ffmpeg with the avisynth script, exctract the frames and make the gif, just a few popup forms to set the parameters and the rest is automated :)

Still a work in progress that needs polishing but works nicely for now, only a bit slow due to no openmp on windows so now i'm wondering if it is possible somehow to grossly get an estimated size for the .gif before it is created. It doesn't need to be very precise tho.

I often need to create a few times the gif with different width/height (or quality setting) to comply with something acceptable i can upload and not end with a file too big, and with the slow speed to create the gif it can be painful so if i am able to get a rough size estimation directly in my script before launching the work it will be very helpful.

If you have any tips or ideas about a mathematical formula to get an estimated size based on the number of frames the gif will have, the quality selected for the gif and width & height maybe ? 

Thanks a lot in advance.

**Comment by kornelski** [comment]
https://github.com/sindresorhus/gifski-app/issues/1#issuecomment-366476444

    width * height * frames / 3 * (quality + 1.5) / 2.5

**Comment by jalba69** [comment]
Fantastic, thanks a lot for the quick reply.

Did not had the idea to look on the gifski-app git not using any apple device but I'll do the next time i'll have some other questions before bothering you here.

You can't imagine how helpful this will be for me.

Thanks again for all :)

closing this -

**Comment by kornelski** [comment]
No problem :)

**Comment by jalba69** [comment]
Hello Kornelski,

Sorry for re-opening this but before i go further i need to be sure i am not doing something wrong.

Finished my powershell thing and started to run intensive tests but something is not adding up with estimation of size, so i added some more functions to log in sizes estimations in my script vs and sizes really created and well i'm wondering now ...

Formula i use for bytes is this : 
`$Bytes_Size = [math]::Round(((([int]$Width * [int]$Height * [int]$framecount) / 3) * (([int]$quality_setting_Input / 100 ) + 1.5)) / 2.5)`

To be more clear it's 
`( ( ( (Width * Height * Number of Frames) /3) * ( (Quality /100) +1.5) ) /2.5 )`

If i made no errors the quality setting is from range 0.1 to 1 , not 1 to 100 like i use in my input parameters, this is why i do the (quality /100).
Anyways i run some semi automated testings with logging to csv and after a bit of analyze it seems totally off as you can see here : 

![2018-03-06_005543](https://user-images.githubusercontent.com/15131985/37006949-26d37a28-20db-11e8-90ce-77e7ccb36ac3.png)
Click to enlarge

All done with quality 100 for those first initial tests, the resizes are made before creating the frames, it ain't gifski managing this in those tests. Just 256 frames from 4 video sources, resized in Staxrip with a avisynth filter then the avisynth script sent to ffmpeg for the frames extraction ,then gifski does his job.

Looked into the link you provided and there the discussion seems to be for videos directly feeding GifSki so i'm wondering if the formula is also valid when feeding it with png's created with ffmpeg like i do ( they are 24 bits png's if i make no error ) 
 
There is a few results not too bad for the HQcartoon at mid sizes resolutions, r the cartoon in high resolution or tiny ones the values are off by a good margin, when it comes to real videos footage it's totally off

Not sure if you have any guess on this, maybe it is normal and best accuracy i can get guessing the sizes, of if using png's messes the formula compared to feeding it with videos directly.

My work is almost done but this isn't adding up for me so i need to be sure that either i did not interpreted the formula wrong or that the png's or something else gives some funky results, then i'll start to run some testings with quality changes and log this to see results too.

Thanks again and sorry for bothering you with this :)

**Comment by kornelski** [comment]
The estimate is inaccurate, because the actual file size depends on amount of color, noise an movement in the clip, which isn't known in advance.

If you have actual data, you can come up with a better estimate :)

**Comment by jalba69** [comment]
Thanks a lot,

That's what i was afraid of :p 

The ones that were more accurate were a HD cartoon with very low movement and while the cartoon is having a lot of details there isn't a lot of colors compared to some of the videos i tested.

I'll do some more testing with logging and might try to come up with something a bit more accurate if i find a pattern in the results, then i can add a simple select setting on my script like 
```
Movement - Scenes changes "slow/medium/very_high"
Colors " Cartoon - low colors/ low res video- medium colors/ HQ res video - High colors " 
```
And selected a mulitiplicator for the calculated size, this is if i manage to get a half decent pattern after running many tests on various footage to start with :p 

--
Or maybe avisynth can come up handy for this with global motion tools plugins and some plugins for colors detection that might be able to perform an analyze uphill, this analyze can then be automated in Staxrip/avisynth script and get a value that will serve as adjustment value for the size estimation i guess. 

Well... a lot of things to study and test and load of work but it's an interesting option to explore :)

Thanks again 

Closing this for good now, will take me some time to explore those possible options, my powershell script is ready and works inside Staxrip, the good thing is that used in Staxrip i can change the video fps, add some overlays/ text on the gif easily, add some color or video filters or whatever is possible with avisynth before sending the result to ffmpeg then to Gifski, and get very nice HQ Gifs in a few clicks only :) 

Thanks a lot for your help :)
