### ISSUE TITLE
Add global palette support

### ISSUE THREAD

**Issue by guijan** [ImageOptim/gifski#284]
Currently, gifski always uses per-frame palettes. This creates larger GIFs. A single global palette reduces file size and may be good enough for some GIFs.

**Comment by kornelski** [comment]
I don't plan to support the global palette. The cost of a local palette is only up to 768 bytes per frame, but it can make frame LZW data smaller by using fewer colors and/or having better-fitting colors that make lossy LZW compression more effective.
