### ISSUE TITLE
support for animated svg => gif

### ISSUE THREAD

**Issue by transitive-bullshit** [ImageOptim/gifski#29]
This would be a really useful addition for making gifski the swiss-army knife of converting to gif.

My specific use case is for screencasts created from [asciinema](https://asciinema.org/) via [svg-term](https://github.com/marionebl/svg-term-cli).

**Comment by kornelski** [comment]
Do you know a tool that can decode an animated SVG?

**Comment by transitive-bullshit** [comment]
Nevermind; the animated svgs I was referencing were using CSS keyframes internally.
