### ISSUE TITLE
CLI produces different colour results from Mac App

### ISSUE THREAD

**Issue by chechoribero** [ImageOptim/gifski#291]
I've been using the Mac App to convert mp4 and mov files, which produces accurate colours when compared to the original video files. However, I'm trying to use the CLI to do batch conversion but the colours look noticeably darker when compared to both the original video file and the Mac App results.

This is the command I'm using in the terminal:
```
gifski --fps 30 --extra -Q 100 -o file.gif file.mp4
```

Both the fps and quality settings are set to the same values in the Mac App and both conversions are using the same file as input.

**Comment by kornelski** [comment]
They use a different video decoder. CLI uses ffmpeg, and the Mac App uses Apple's video decoder. 

Do you get better result if you use `ffmpeg -i file.mp4 frame%04d.png` and make GIF from the PNGs?

**Comment by chechoribero** [comment]
The results are the same, although if I export a png sequence from After Effects and bypass the mp4 altogether it seems to work fine. The problem seems to be the conversion from video to png.
