### ISSUE TITLE
Previous frame disposing + moiré pattern issues

### ISSUE THREAD

**Issue by ThomasKliszowski** [ImageOptim/gifski#293]
Hello 👋

First of all, thanks for your job on improving GIF rendering 🙏

## Problem
I am encountering 2 problems using Gifski:
 - the moiré pattern is really huge when an element fades in / out
 - the disposing of a previous frame is sometimes missed

![appstore](https://user-images.githubusercontent.com/1174135/225591667-51d2381d-b26c-4f74-9de1-e53403639124.gif)

## Repro

Use these frames [appstore.zip](https://github.com/ImageOptim/gifski/files/10989628/appstore.zip) and unzip in `appstore`.

```
cargo run -- --quality 100 --fps 50 --output appstore.gif appstore/*
```

## Other examples

Frame disposing issue [like.zip](https://github.com/ImageOptim/gifski/files/10989728/like.zip)
![like](https://user-images.githubusercontent.com/1174135/225595804-f700fbda-0e19-44ad-a389-c5b518b4b07a.gif)

Moiré pattern + frame disposing issue [profile.zip](https://github.com/ImageOptim/gifski/files/10989780/profile.zip)
![profile](https://user-images.githubusercontent.com/1174135/225597197-31ad8c14-26ae-4954-967d-f063e8bf64d9.gif)

**Comment by kornelski** [comment]
The dithering pattern in semitransparency is expected and largely unavoidable, because GIF doesn't support alpha transparency. Give the animation a solid white background to avoid the dithering.

I'll have a look at the disposal bugs.

**Comment by ThomasKliszowski** [comment]
Alright, thanks for the disposal bugs 👍 

Ah indeed, you are right about the dithering 👌 
What do you think about exposing a setting to enable / disable the dithering?

In my case, disabling it gives better results:
![1c6b50e4-f9d6-4c3e-90e3-8933f897a8d6](https://user-images.githubusercontent.com/1174135/225651375-9a431b4e-5819-4ef5-8a5b-fd4aaf4d92da.gif)

**Comment by kornelski** [comment]
Disposal is fixed. 

You can control the transparency when making input images, so I think I'll leave that as-is.
