### ISSUE TITLE
Unable to find the input file with wildcard

### ISSUE THREAD

**Issue by qayyumabro** [ImageOptim/gifski#294]
Hi, its throwing an error on Windows 11.

Error output: error: Unable to find the input file: "C:\Users\user\AppData\Local\Temp\7849c489-48ce-485f-9e54-75e4bfeedc28_*.png"
Error output: The path contains a literal "*" character. Either no files matched the pattern, or the pattern was in quotes.

images exist:
![image](https://user-images.githubusercontent.com/9138521/228827780-81a23d20-f30d-442d-9669-0b095689e150.png)

**Comment by kornelski** [comment]
> The path contains a literal "*" character. Either no files matched the pattern, or **the pattern was in quotes**.

When you put `"*"` in quotes it means filenames that have star in the name. If you write `*` without quotes, it means a pattern.
