### ISSUE TITLE
Command line tool for windows 1.11 doesn't work

### ISSUE THREAD

**Issue by DemonikGH** [ImageOptim/gifski#298]
Downloaded latest version of command line tool but it does nothing, it runs for a bit but there is no output, no errors or anything. No commands work, even just `gifski -h`. Tried using it to create gif from both video or frames - neither work. GUI tool works but it lacks options.

Windows version - 10 19045.2846.

Built from source works - only pre-built download doesn't.

**Comment by kornelski** [comment]
This is Microsoft blocking unknown executables. It's a new file, so until somebody uses Edge to download it and clicks "Report this as safe" option, Microsoft will keep blocking it as potential malware.

I can't do anything about it. The proper way Microsoft wants to solve this is to have developers use code signing, but their certificates can only be obtained from commercial vendors. Microsoft's tooling for signing is absolutely atrocious — every single option there is some kind of a gotcha with a wrong and outdated default. It's half-documented in shreds spread over dozens of MSDN pages. All of this seems to be abandoned after Windows XP. I don't have enough patience to deal with code signing, so all Windows executables I produce are doomed to be frequently blocked by Microsoft.

**Comment by kornelski** [comment]
The report option should be there, but it's not for the exe, but for the zip file as a whole, in Edge's downloads dropdown.

Also if you double-click it from Explorer you should get the standard scary "Don't Run" message.

**Comment by kornelski** [comment]
Ok, that's odd. In that case I'm not familiar with such problem.
