### ISSUE TITLE
"spotch" artifacts , ?dithering or ?quant artifacts ?

### ISSUE THREAD

**Issue by pdr0github** [ImageOptim/gifski#30]
First, thanks for the tool - I just heard about it recently

Some artifacts generated around deadpool's ear. I circled it in this single frame preview. No artifacts of this kind with other methods. 3/56 frames affected
https://s9.postimg.org/tuue0bvtb/splotch.png

Not sure if they are quantization artifacts , dithering artifacts or something else. I didn't have time to do other testing yet

Source images and final gif . (Source was section from Deadpool 1 YT trailer, cropped, trimmed in avisynth to png sequence)
~21Mb zip archive
http://www.mediafire.com/file/zdeykyjnq07lrcg/giftest.zip

cmd used (0.8.2)
[code]
gifski.exe --fps 15 -o gifski.gif giftest*.png
[/code]

**Comment by kornelski** [comment]
It looks like gifski decided that the difference between frames here is minimal and doesn't need update between frames, probably because that area is dark. It needs some tuning.

![gifski gif 022](https://user-images.githubusercontent.com/72159/37204327-58ef0432-2388-11e8-8214-cb1f50c19a21.gif)

**Comment by kornelski** [comment]
This should be fixed now
