### ISSUE TITLE
[Feature Request] add way to control metadata

### ISSUE THREAD

**Issue by alexmozaidze** [ImageOptim/gifski#303]
Add something like `--no-metadata/-m` or `--pure/-p` to remove all metadata from the output file.

# Reason

Privacy. When I post a gif, someone could analyze and find out I used gifski for creating the gif. I have to remove metadata after I run gifski, which is inconvenient.

**Comment by kornelski** [comment]
It's possible to tell a GIF has been made with gifski even without metadata. It generates palettes in a unique way that no other tool does.

**Comment by alexmozaidze** [comment]
Fair
