### ISSUE TITLE
Resize wont work?

### ISSUE THREAD

**Issue by DarkRyuk12345** [ImageOptim/gifski#304]
Hello there, I have recently learned about gifski and wanted to use it to resize GIF files. Since it seemed fast and reliable and had a rust binding. Now, to test it, i tried using the cli to resize a GIF. I ran the command below:

```bash
gifski --width 1080 --height 1920  -o test_resized.gif test.gif
```

Now the command ran fine and succeeded, which was exciting. Except when I saw the image size, it was the same(320x114) as before, according to both Nautilus and Chrome! 

Which didn't exactly fit my needs, and I couldn't find anything online either, so I decided to ask here.

Thats all, thanks.

**Comment by kornelski** [comment]
It never makes sense to make a gif bigger. It is a pure waste of data, so gifski will never do it.

Use width/height in HTML and object-fit in CSS.

Or use higher-quality source images.

**Comment by DarkRyuk12345** [comment]
> It never makes sense to make a gif bigger. It is a pure waste of data, so gifski will never do it.
> 
> Use width/height in HTML and object-fit in CSS to display gifs at larger size.
> 
> Or use higher-quality source images.

I am using gtk, so I don't think I can do either of those, unfortunately. unless gtk css allows that, which I am sure it doesn't.

**Comment by DarkRyuk12345** [comment]
Alright, never mind. I found a workaround. Using gtk's picture fit property.
