### ISSUE TITLE
Motion & Lossy quality question.

### ISSUE THREAD

**Issue by theShiZa** [ImageOptim/gifski#305]
Hi.

Can you please tell me GIFski's default values for --motion-quality & --lossy-quality settings if I don't specify them?
Are they max 100 by default if I don't use them when creating?

Thanks.

**Comment by kornelski** [comment]
If they're not set explicitly, they're the same as the general quality setting.

**Comment by theShiZa** [comment]
kornelski, the man himself!  Thanks heaps for your awesome GIFski, it's excellent.

Just to confirm, do you mean same as in if I set --quality to 100, but don't set motion & lossy explicitly, then they're both automatically 100 also? 
Thanks for your time Sir.

**Comment by kornelski** [comment]
Yes.

**Comment by theShiZa** [comment]
Excellent, thanks so much.

**Comment by theShiZa** [comment]
Excellent, thanks so much.
