### ISSUE TITLE
Feature request: Boomerang effect

### ISSUE THREAD

**Issue by Laurent2916** [ImageOptim/gifski#306]
Hi,
Very impressive project, well done!
The software already allows users to loop the gif, would it be possible to add a function allowing a "boomerang effect"?

Here is an exemple with the gif from the README:
![](https://camo.githubusercontent.com/eda952606e44946107dd462367cf1617b6e4d69d12da473328b31109b6ebe338/68747470733a2f2f6769662e736b692f64656d6f2e676966)
![](https://github.com/ImageOptim/gifski/assets/21087104/4dba931a-458e-44b2-a1e7-9a80f63ab689)

**Comment by kornelski** [comment]
GIF doesn't support this. It requires adding all of the frames again, as if they were brand new frames. I don't want to get into video editing with this tool. You will need to duplicate and reverse the frames yourself.
