### ISSUE TITLE
Illegal instruction (core dumped) error on Ubuntu 22.04

### ISSUE THREAD

**Issue by serpentinesr** [ImageOptim/gifski#310]
Was working fine before. Recently reinstalled Ubuntu and tried to install gifski through the deb package. when i run gifski -h, it just prints this to the terminal: Illegal instruction (core dumped)

**Comment by kornelski** [comment]
What CPU do you have? Does it support AVX?

**Comment by serpentinesr** [comment]
Hey actually it fixed itself, i think. Got the snap version on Ubuntu.
Appreciate your reply.
