### ISSUE TITLE
Conversion fails with brackets in folder path

### ISSUE THREAD

**Issue by SheriffBuzz** [ImageOptim/gifski#314]
OS: Windows 10
 CLI version: 1.11.0

I run the following command:

`bin\gifski.exe -o "K:\render\Render[1]~Dance\backgroundwhite.gif" --quality 100 --repeat 0 --extra --fps 24 K:\render\Render[1]~Dance\backgroundwhite\*.png`

```
error: Unable to find the input file: "K:\render\Render[1]~Dance\backgroundwhite\*.png"
The "*" character was in quotes, which disabled pattern matching. The file with an actual literal asterisk in its name obviously doesn't exist.
To search for all files matching a pattern, use * without quotes.
```

This command had brackets in the folder path. If I duplicate the folder path and replace the brackets with parenthesis and pass this command it works.

`bin\gifski.exe -o "K:\render\Render[1]~Dance\backgroundwhite.gif" --quality 100 --repeat 0 --extra --fps 24 K:\render\Render(1)~Dance\backgroundwhite\*.png`

It appears it is interpreting the brackets as special characters, although they are not even in the deepest/leaf folder segment. The folder path is not quoted in the command, either. I do not see anything in the readme indicating brackets are special characters or cannot be used.

**Comment by kornelski** [comment]
The rule is: 

* outside of quotes, `[]` and `*` are special characters for glob matching.
* inside quotes `[]` means exactly `[]` and nothing else, and `*` means exactly file name with this `*` in it, and no other files.

Don't put quotes around special characters if you want them to work. Put quotes around special characters if you want them treated like plain text in file names.
