### ISSUE TITLE
Upgrade shlex to version 1.3.0 

### ISSUE THREAD

**Issue by davidjharder** [ImageOptim/gifski#319]
Hi, I'm part of a linux distribution (Solus) that packages gifski. 
We're getting a dependabot notification that the `shlex` crate should be upgraded.

**Comment by davidjharder** [comment]
Sorry, I see your most recent tag fixes this. Nevermind

**Comment by kornelski** [comment]
This notification is nonsense anyway. Even in the old verison shlex was used only at build time of ffmpeg dependency, only with trusted inputs, and the affected methods weren't even used at all.

**Comment by davidjharder** [comment]
Thanks for the response.
