### ISSUE TITLE
Version 1.14 notifiying that new version available

### ISSUE THREAD

**Issue by inoyakaigor** [ImageOptim/gifski#321]
It's not that should be fixed asap, just confusing me

1) Just installed latest Gifski version 1.14 from Github
2) Clicked to «A new version available»
3) At site clicked to the «Download» button
4) Oldest 1.12 version has been dowloaded
<img width="1613" alt="image" src="https://github.com/ImageOptim/gifski/assets/1235286/1071b3f4-0b25-4a53-864c-08fa5700e7c3">

**Comment by kornelski** [comment]
Try installing http://gif.ski/gifski_1.14.1_x64_en-US.msi.zip

**Comment by inoyakaigor** [comment]
Still notifiying 
![image](https://github.com/ImageOptim/gifski/assets/1235286/91bf7277-7aa4-4ba6-b5e3-f91eb7f8d5d7)
