### ISSUE TITLE
Here are some shadows on white background gif.

### ISSUE THREAD

**Issue by imfantuan** [ImageOptim/gifski#322]
Original:
![starbucks](https://github.com/ImageOptim/gifski/assets/16457655/8a9ecdfe-d461-472e-ba21-16879ff60af9)

gifski
```
gifski --fast -W 1000 --motion-quality 90 /Users/nicol/feikuai.gif -o /Users/nicol/feikuai.quant.gif
```
![starbucks gifski](https://github.com/ImageOptim/gifski/assets/16457655/b86d3555-067f-488b-9129-f86aa2bcccef)

**Comment by kornelski** [comment]
Thanks for the report. Fixed.
