### ISSUE TITLE
Error in example script for FFMPEG usage of yuv4mpegpipe

### ISSUE THREAD

**Issue by Udinanon** [ImageOptim/gifski#329]
I wanted to point out that the example provided in teh README and in the help message when gifski fails has a missing command

`ffmeg -i video.mp4 -f yuv4mpegpipe | gifski -o anim.gif -` fails, as ffmpeg laments a missing output and figski laments not supporting videos
```
ffmpeg -i resources/raw/lake.mp4 -f yuv4mpegpipe | gifski -o anim.gif -
ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 14 (GCC)
[...]
At least one output file must be specified
error: Video support is permanently disabled in this distribution of gifski.

The only 'video' format supported at this time is YUV4MPEG2, which can be piped from ffmpeg:

    ffmpeg -i "video.mp4" -f yuv4mpegpipe | gifski -o "video.gif" -

To enable full video decoding you need to recompile gifski from source.
https://github.com/imageoptim/gifski

Alternatively, use ffmpeg or other tool to export PNG frames, and then specify
the PNG files as input for this executable. Instructions on https://gif.ski
```

The correct format of the command should be
`ffmpeg -i video.mp4 -f yuv4mpegpipe - | gifski -o anim.gif -`
telling ffmpeg to pass its output via stdin
 
Amazing project for everything else! It's incredible how good GIFs can look

**Comment by kornelski** [comment]
Thanks
