### ISSUE TITLE
Feature request: generate gif as palindrome

### ISSUE THREAD

**Issue by MrDrMcCoy** [ImageOptim/gifski#332]
Love this project, and thank you for all your hard work on it!

I sometimes encounter sequences that would work best as a palindrome. It would be very convenient if `gifski` had a `--palindrome` flag that would copy the image sequence in reverse and append it to the end before finalizing the file. Would this be terribly difficult to implement?

**Comment by kornelski** [comment]
You could create/export extra frames for this. 
There is nothing in the GIF format to make that more efficient. It's just more animation.

It's not too hard for frames given as separate files, but pretty cumbersome for video.
