### ISSUE TITLE
About err code 3 (GIFSKI_QUANT)

### ISSUE THREAD

**Issue by mojie126** [ImageOptim/gifski#335]
Regardless of whether I use `gifski_add_frame_png_file` or `gifski_add_frame_rgba`, the error code 3 (GIFSKI_QUANT) is returned when calling `gifski_finish`. If it means that I did not quantize the palette, my PNG image uses 8-bit color depth. How can I solve this problem?

**Comment by kornelski** [comment]
Fixed on main branch too.
