### ISSUE TITLE
Pipe frames to gifski using stdin

### ISSUE THREAD

**Issue by facuparedes-litebox** [ImageOptim/gifski#337]
Hi everyone! First of all, thank you for creating Gifski, we are using it to develop an application, and we are impressed by the processing speed and the size of the files it generates.
However, a bottleneck for us today is writing the frames to a directory so that gifski can read them. In our case, the ideal is to stream all the frames directly to gifski using pipes through stdin.
I saw that Gifski already supports an input pipe with videos, but in my tests, I couldn't get it to work with just images.

I also found this issue that I think might be related:
https://github.com/ImageOptim/gifski/issues/223

Can you help us?

**Comment by kornelski** [comment]
This is already supported via y4m uncompressed video format.

**Comment by facuparedes-litebox** [comment]
Thanks u! I was able to convert my png to y4m in my code and then stream the y4m frames to gifski without problems
