### ISSUE TITLE
Artefacts and pixelation

### ISSUE THREAD

**Issue by martinObennett** [ImageOptim/gifski#340]
Hey 

I’ve been using Gifski for a while and its been fantastic 

But since upgrading my mac to OS 15 Sequoia it’s not working. 
I get lots  of pixel artefacts in the videos. 

I also tried the latest Beta on TestFlight and got the same results

Have you had any similar issues? 

Do you have any suggestions on how i can rectify this?

I'm converting mp4s 1920x1080 scaling down to 1280x720 the quality set to around 90% 

This has always produced great results in the past but now as you can see the quality is just not there. 

Many thanks

Martin

![The New MercedesAMG GT S TVC Dreamcar_test2](https://github.com/user-attachments/assets/a4ba704e-75e1-42a1-ac2c-307d772c0105)

**Comment by kornelski** [comment]
Square artifacts are from video codecs, not from GIF encoding. This seems to be caused by problems with video decoding in macOS.

The GUI and Mac video decoding part is implemented by another project, so please report it over there:

https://github.com/sindresorhus/Gifski
