### ISSUE TITLE
docs(install): Could you please add the steps to install gifski using x-cmd to this document?

### ISSUE THREAD

**Issue by lunrenyi** [ImageOptim/gifski#342]
- Hi, [x-cmd](https://www.x-cmd.com/) is a **toolbox for Posix Shell**, offering a lightweight package manager built using shell and awk.. It helps you download gifski release packages from the internet and extract them into a unified directory for management, without requiring root permissions.

- **I mean, can the installation method provided by x-cmd be added to the gifski installation.md?**[The installation method for the x command](https://www.x-cmd.com/start/).
  ```sh
  x env use gifski
  ```

- We wrote a [gifski introduction article](https://www.x-cmd.com/pkg/gifski) and a [demo](https://bilibili.com/video/BV1Zc2dYkE3m/)

**Comment by kornelski** [comment]
Thanks for packaging it. x-cmd looks like a cool project, but I prefer to distribute executables myself, and I can't take responsibility for executables distributed outside of my control.

Please note that you're required to distribute the license file along with the program. Your build archives don't contain the license: https://github.com/x-cmd-build/gifski/releases Almost all open-source licenses have this requirement.

**Comment by lunrenyi** [comment]
Okay, thanks for your reply!
