### ISSUE TITLE
Gifski renders Half resolution Gifs, pretty often

### ISSUE THREAD

**Issue by progreso** [ImageOptim/gifski#343]
sometimes it renders on half resolution and I can not do anything about it. for example I attached small image sequence I rendered from AE, it is 1400x840...when I am trying to create gif with Gifski it gives me 700x420 resolution...I tried couple other sequences and this weird thing comes and goes, some sequence it renders as is and some sequence it reduces resolution, I tried rerender from AE in many forms but no effect. on some images it always reduces resolution.

[img_seq.zip](https://github.com/user-attachments/files/18256386/img_seq.zip)

version 1.14.4 on windows 10...I tried different quality modes, fps, but nothing seems to fix it.

**Comment by kornelski** [comment]
This is done deliberately. GIF is a primitive video format, not equipped to deal with HD resolutions. 

I treat any attempt to use resolutions higher than 800x600 as a mistake, and fix it by halving the output resolution in such case. 
You can override that by specifying `--width` CLI flag explicitly, but I suggest not to fight this. 

GIF is really bad at handling high resolutions, and even advanced compressor like gif.ski can't do much about this. GIF can't even compress empty space efficiently. GIF uses a text compression algorithm from 1980s, which wasn't even good for compressing text back then. 

If you need a high resolution video, you should use anything else other than GIF. AV1 or VP9 video would be the best.

**Comment by progreso** [comment]
oh thank you. I was using GUI version, am not a CLI guy. it worked YEES....would be very helpful if GUI version would give warning or something in that case, I was very confused because it did render 1400pix gifs on some sequences before. anyhow, am glad I can make it work and I hope in future GUI version will have all those CLI features implemented, cheers
