### ISSUE TITLE
which  version of rust to install gifski ???

### ISSUE THREAD

**Issue by khelmrab** [ImageOptim/gifski#36]
hello , 
I am trying to install gifski on Windows with: cargo install gifski
I tested with version 1.20.0 1.24.0 1.19.0 1.5.0 1.8.0 
None of them worked. I still have errors. 

errors with version 1.22.0
error[E0308]: mismatched types
   --> c\....\cargo\registry\src\github.com-1ecc6299db9ec823\lodepng-2.1.4\src\ffi.rs:388:47

errors with version 1.20.0:
error: use of unstable library feature 'ord_max_min' (see issue #25663)
   --> C:\...\.cargo\registry\src\github.com-1ecc6299db9ec823\imgref-1.3.3\src\lib.rs:135:44
    |
135 |         let non_padded = &buf[0..buf.len().min(stride * self.height())];
    |                                            ^^^

   Compiling memoffset v0.2.1

@kornelski

**Comment by kornelski** [comment]
I'm generally only testing with the latest stable (Rust 1.24).

I temporarily broke some stuff in lodepng on Windows. If you run `cargo update` it should get the latest version, which is fixed.

**Comment by kornelski** [comment]
1.28
