### ISSUE TITLE
could not find `Cargo.toml`

### ISSUE THREAD

**Issue by euppi98** [ImageOptim/gifski#41]
I get an error when executing the command: cargo build --release --features=video
![screen shot 2018-05-15 at 14 44 00](https://user-images.githubusercontent.com/23306157/40054691-6cab5ed0-584e-11e8-9ff0-cf97e86c790a.png)

**Comment by kornelski** [comment]
You have to clone the repository first and then `cd` to it.

**Comment by euppi98** [comment]
Okay, with the command "cargo build -release", everything is fine. But the command "cargo build -release --features = video" gives this error:
![screen shot 2018-05-15 at 17 51 06](https://user-images.githubusercontent.com/23306157/40064848-0a4e8d64-5869-11e8-8dfb-781d6594d348.png)

**Comment by euppi98** [comment]
"llvm + clang" - Can I install it with "brew"?

**Comment by euppi98** [comment]
Okay, maybe we are can somehow rationally solve this question? Let's imagine that I have a clean system... What should I do?

**Comment by euppi98** [comment]
Okay, as far as I understand, ffmpeg convert from video to gif?

**Comment by euppi98** [comment]
Well, I think I see a solution to the problem. Just install ffmpeg 3.4.2, not 4.0. Will it work?

**Comment by kornelski** [comment]
It would help. I'm not sure if it still won't try to use clang+llvm (required by ffmpeg-sys -> bindgen, which translates C's .h to Rust's). At least you must have Xcode tools installed.

**Comment by euppi98** [comment]
Do not know how to install the old version of ffmpeg through the brew? I do not know how to compile files.

**Comment by kornelski** [comment]
That's part of the problem. Installing old things from Homebrew is not supported and you need hacks. It's going to be hard.

**Comment by euppi98** [comment]
And why can not you add support for ffmpeg 4?

**Comment by kornelski** [comment]
I'm planning to remove ffmpeg completely and switch to gstreamer, but I'm busy with higher-priority things.

**Comment by euppi98** [comment]
Why? Than you so do not like ffmpeg?

**Comment by euppi98** [comment]
If you delete, then in the future we are can not convert from video to gif...

**Comment by kornelski** [comment]
You can convert video to gif. Please use `ffmpeg -i %04d.png`, as explained on the website.

**Comment by euppi98** [comment]
It is not comfortable

**Comment by euppi98** [comment]
I work as a designer, and I very often have to convert from video to gif.

**Comment by kornelski** [comment]
Then use the version of gifski for designers: https://itunes.apple.com/no/app/gifski/id1351639930?mt=12

**Comment by euppi98** [comment]
Nice!
![screen shot 2018-05-16 at 11 40 02](https://user-images.githubusercontent.com/23306157/40106266-f3d344c2-58fd-11e8-9a60-f4e2c2ba4eb5.png)

**Comment by euppi98** [comment]
It is more convenient for me to work with the terminal than with any program. After converting the video into a hyph, I immediately compress the hyph into the terminal using - giflossy
