### ISSUE TITLE
Website IPv6 support

### ISSUE THREAD

**Issue by tambry** [ImageOptim/gifski#42]
The website is inaccessible over IPv6.

Seems like this is a matter of adding [2a01:488:66:1000:53a9:244:0:1] (the IPv6 address for ImageOptim's website) to DNS, as fetching gif.ski from it works:
```
> curl https://[2a01:488:66:1000:53a9:244:0:1] -H "Host:gif.ski" -k
<!DOCTYPE html>
<meta charset=utf8>
<title>gifski ÔÇö highest-quality GIF converter</title>
[...]
```

**Comment by kornelski** [comment]
Fixed
