### ISSUE TITLE
FTBFS: gif version mismatch

### ISSUE THREAD

**Issue by orac** [ImageOptim/gifski#43]
I just now tried to install on stable-x86_64-pc-windows-msvc with rustc 1.26.2, and I get the following error:

        Updating registry `https://github.com/rust-lang/crates.io-index`
      Installing gifski v0.8.3
       Compiling nodrop v0.1.12
       Compiling cfg-if v0.1.3
       Compiling winapi v0.3.5
       Compiling memoffset v0.2.1
       Compiling lazy_static v1.0.1
       Compiling cc v1.0.17
       Compiling winapi-build v0.1.1
       Compiling scopeguard v0.3.3
       Compiling rayon-core v1.4.0
       Compiling libc v0.2.42
       Compiling color_quant v1.0.0
       Compiling rgb v0.8.9
       Compiling unicode-width v0.1.5
       Compiling rustc-demangle v0.1.8
       Compiling lzw v0.10.0
       Compiling winapi v0.2.8
       Compiling glob v0.2.11
       Compiling vec_map v0.8.1
       Compiling strsim v0.7.0
       Compiling imgref v1.3.4
       Compiling either v1.5.0
       Compiling bitflags v1.0.3
       Compiling resize v0.3.0
       Compiling crossbeam-utils v0.2.2
       Compiling arrayvec v0.4.7
       Compiling num_cpus v1.8.0
       Compiling textwrap v0.9.0
       Compiling kernel32-sys v0.2.2
       Compiling lodepng v2.1.5
       Compiling gif v0.10.0
       Compiling gif v0.9.2
       Compiling wild v0.1.1
       Compiling crossbeam-epoch v0.3.1
       Compiling imagequant-sys v2.12.0
       Compiling gif-dispose v2.1.1
       Compiling crossbeam-deque v0.2.0
       Compiling imagequant v2.11.9
       Compiling rand v0.4.2
       Compiling time v0.1.40
       Compiling backtrace v0.3.8
       Compiling atty v0.2.10
       Compiling clap v2.31.2
       Compiling error-chain v0.11.0
       Compiling rayon v0.9.0
       Compiling pbr v1.0.1
       Compiling gifski v0.8.3
    error[E0308]: mismatched types
       --> src/lib.rs:358:43
        |
    358 |             screen.blit(Some(&frame.pal), dispose, 0, 0, frame.image.as_ref(), transparent_index)?;
        |                                           ^^^^^^^ expected enum `gif::common::DisposalMethod`, found enum `gif::DisposalMethod`
        |
        = note: expected type `gif::common::DisposalMethod`
                   found type `gif::DisposalMethod`
    note: Perhaps two different versions of crate `gif` are being used?
       --> src/lib.rs:358:43
        |
    358 |             screen.blit(Some(&frame.pal), dispose, 0, 0, frame.image.as_ref(), transparent_index)?;
        |                                           ^^^^^^^

    error: aborting due to previous error

    For more information about this error, try `rustc --explain E0308`.
    error: failed to compile `gifski v0.8.3`, intermediate artifacts can be found at `C:\Users\Dan\AppData\Local\Temp\cargo-installAon2GQ`

    Caused by:
      Could not compile `gifski`.

    To learn more, run the command again with --verbose.

Note in particular this part, which seems wrong:

       Compiling gif v0.10.0
       Compiling gif v0.9.2

Does your gif dependency need to be updated to match a transitive dependency?

**Comment by kornelski** [comment]
This has been fixed in master
