### ISSUE TITLE
Installation on ubuntu 17.10 fails

### ISSUE THREAD

**Issue by herrwusel** [ImageOptim/gifski#44]
Tried to run ``cargo install gifski`` but it fails:

> Compiling gifski v0.8.3
> error[E0308]: mismatched types
>    --> src/lib.rs:358:43
>     |
> 358 |             screen.blit(Some(&frame.pal), dispose, 0, 0, frame.image.as_ref(), transparent_index)?;
>     |                                           ^^^^^^^ expected enum `gif::common::DisposalMethod`, found enum `gif::DisposalMethod`
>     |
>     = note: expected type `gif::common::DisposalMethod`
>                found type `gif::DisposalMethod`
> note: Perhaps two different versions of crate `gif` are being used?
>    --> src/lib.rs:358:43
>     |
> 358 |             screen.blit(Some(&frame.pal), dispose, 0, 0, frame.image.as_ref(), transparent_index)?;
>     |                                           ^^^^^^^
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0308`.
> error: failed to compile `gifski v0.8.3`, intermediate artifacts can be found at `/tmp/cargo-installOeuOri`
> 
> Caused by:
>   Could not compile `gifski`.
> 
> To learn more, run the command again with --verbose.

Building works fine for me.

**Comment by kornelski** [comment]
I've published v0.8.4 that fixes this.
