### ISSUE TITLE
Option to turn off dithering - useful with screencasts where little changes on screen

### ISSUE THREAD

**Issue by JobLeonard** [ImageOptim/gifski#49]
I guess this might sound like it defeats the purpose of gifski, but when turning a screencapture into a gif, usually the frame-to-frame changes are absolutely minimal. It usually makes more sense to either turn off dithering, or to use a stable dithering option in that case.

gifski uses pngquant under the hood, right? And that already supports turning off FS dithering with `--nofs` for precisely this kind of use case (but I don't know how much work it is to integrate that with gifski of course).

For comparison, GIMP does both better and worse at this: I just tried converting a 2,1 MiB mp4, recordging of a short Full HD screen grab. processed with gifski it becomes a 54,8 MiB gif, with GIMP 14,3. However, GIMP takes a lot more time to generate the output, generates uglier colors than gifski, and _somehow_ the resulting gif also manages to be a lot more sluggish to play back.

**Comment by kornelski** [comment]
Gifski always tries to improve the previous frame in the diff with the next frame. Sometimes that backfires when it can't improve quality and actually makes it worse, and it ends up improving/degrading the frame over and over. That adds up data on static backgrounds. I should probably detect it and/or add some temporal denoising algorithm in there, but I've been busy with other projects lately.

Other than that file size is not really a focus in gifski. I've mainly intended it to limit damage when animations have to be uploaded as GIF to sites that will display them as video anyway (as every site should).

**Comment by JobLeonard** [comment]
> Gifski always tries to improve the previous frame in the diff with the next frame. Sometimes that backfires when it can't improve quality and actually makes it worse, and it ends up improving/degrading the frame over and over. That adds up data on static backgrounds. 

This feels conceptually really similar to [the difference in seam carving when using backward and forward energy](https://github.com/axu2/improved-seam-carving)

I totally understand that this is neither the focus of the project, nor that you have much spare time for it. I'm already grateful for the existence of this free tool! :)

**Comment by kornelski** [comment]
Try 0.10.1. I've fixed a bug that could have caused excessive dithering.
