### ISSUE TITLE
Linux != Ubuntu or Debian

### ISSUE THREAD

**Issue by metal3d** [ImageOptim/gifski#52]
Hi, 
I know the title is a bit... enoying :)

But really, in "release" package, try to not call "Linux" Debian only packages... I was so exciting to use it in Fedora/CentOS/RedHat, then I was so disappointed to see a "linux" directory with only .deb file.

(Yes... I will compile it)

Cheers ;)

**Comment by kornelski** [comment]
Yeah, of course. Can you provide a link to the linux reference?

**Comment by kornelski** [comment]
Oh, I see. You mean the directory name in the archive. The website says it's for Debian.

**Comment by schewara** [comment]
I have the same issue as @metal3d 
It would be much appreciated, to also provide packages for other Linux Distros. currently there is only a `.deb` Package available which does not work on distros with a different Packaging format (RPM in my case as well).

An alternative could be to pack a static binary into the release archive as well, as this is commonly done in Go Projects

For example:
https://github.com/terraform-linters/tflint/releases/tag/v0.15.0

The example above also splits up the archives by OS family and architecture which would save additional bandwidth on Server and Client side, as you usually never need the binaries for the other operating systems and would probably also give more insight on which platforms the software is actually used based on the individual downloads.

Kind regards
OSH

**Comment by kornelski** [comment]
I'm using [`cargo-deb`](https://lib.rs/cargo-deb) to make the Debian package, which is really really nice to use. Literally one command, no config.

I don't know any such tool for RPMs. I'm afraid I'd need to maintain a spec file, and have an RPM-based VM or Docker around for the builds. I'm not keen on maintaining that :(

**Comment by metal3d** [comment]
https://github.com/dgoodwin/tito ?

**Comment by metal3d** [comment]
Or simply make a flatpak ?

**Comment by schewara** [comment]
In my case I wanted to have a native package for using with peek, but then I found the flatpak version of it, which has gifski already integrated.

But I can understand the pain of maintaining packages for multiple distros, therefore a static compiled binary would prob. be the most convenient solution for everyone, as it would be distribution agnostic.

**Comment by kornelski** [comment]
If you can prepare something that e.g. Travis or GitHub Actions would build for me, I'm happy to accept it.

**Comment by kornelski** [comment]
In case of Rust, the MUSL target is distro-agnostic.

**Comment by infraengineer-sre** [comment]
```
$ sudo dnf --enablerepo=updates-testing install cargo
[sudo] password for i: 
Fedora 32 - x86_64 - Test Updates                                                                                                                                                                             800 kB/s |  12 MB     00:15    
Last metadata expiration check: 0:00:11 ago on Thu 10 Sep 2020 01:04:39 PM MSK.
Dependencies resolved.
==============================================================================================================================================================================================================================================
 Package                                                     Architecture                                       Version                                                     Repository                                                   Size
==============================================================================================================================================================================================================================================
Installing:
 cargo                                                       x86_64                                             1.46.0-2.fc32                                               updates-testing                                             3.3 M
Installing dependencies:
 rust                                                        x86_64                                             1.46.0-2.fc32                                               updates-testing                                              25 M
 rust-std-static                                             x86_64                                             1.46.0-2.fc32                                               updates-testing                                              16 M

Transaction Summary
==================================================================================================================================================================================================
Install  3 Packages

Total download size: 44 M
Installed size: 163 M
```


```
$ sudo cargo install gifski
    Updating crates.io index
  Downloaded gifski v1.2.1
...
   Compiling gifski v1.2.1
    Finished release [optimized] target(s) in 1m 26s
  Installing /root/.cargo/bin/gifski
   Installed package `gifski v1.2.1` (executable `gifski`)
warning: be sure to add `/root/.cargo/bin` to your PATH to be able to run the installed binaries
```

```
$ cargo --version
cargo 1.45.1
```

```
5.8.4-200.fc32.x86_64 #1 SMP Wed Aug 26 22:28:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Fedora release 32 (Thirty Two)
```

**Comment by ngirard** [comment]
I'm personally using [Nfpm](https://github.com/goreleaser/nfpm). Written in Go. Cannot recommend it enough.

**Comment by porjo** [comment]
I used this on Fedora by unpacking the deb file with `ar` utility.

It'd be nicer if there were a simple tar file containing the binary for Linux without any distro packaging.

**Comment by Zinc-OS** [comment]
_You can just install rust_

**Comment by kornelski** [comment]
I publish musl executables now.
