### ISSUE TITLE
gifski_write() returns GIFSKI_INVALID_STATE

### ISSUE THREAD

**Issue by jeroen** [ImageOptim/gifski#53]
I wrote some bindings for the R programming language. The relevant code is here: https://github.com/r-rust/gifski/blob/master/src/wrapper.c#L36-L68

Everything seems to work, however after I call `gifski_end_adding_frames()` in the main thread, `gifski_write` (in the background thread) returns with GIFSKI_INVALID_STATE instead of GIFSKI_OK.

The resulting gif seems fine though. What am I doing wrong?

**Comment by kornelski** [comment]
I've released v0.8.6 that adds more information about errors.

**Comment by kornelski** [comment]
`gifski_write` is blocking, but `gifski_add_frame_*` and `gifski_end_adding_frames` is non-blocking, so you're dropping the handle.

Write on the main thread, add frames on background thread.

**Comment by jeroen** [comment]
Hmm it also happens if I drop the handle after `pthread_join()` so I'm not sure if that's the problem. But I can try switching around the bg and fg thread...

**Comment by jeroen** [comment]
Unrelated, but I tried to upgrade gifski and I got this error on my linux server:

```
   Compiling pbr v1.0.1
error[E0658]: use of unstable library feature 'fs_read_write' (see issue #46588)
    --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/lodepng-2.4.1/src/rustimpl.rs:3271:5
     |
3271 |     fs::read(filename).map_err(|_| Error(78))
     |     ^^^^^^^^
error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/lodepng-2.4.1/src/huffman.rs:157:18
    |
157 |         .filter(|(_, f)| *f > 0)
    |                  ^^^^^^ help: consider using a reference: `&(_, f)`
error: aborting due to 2 previous errors
error: Could not compile `lodepng`.
```

**Comment by kornelski** [comment]
You need to update rust (`rustup update`). Gifski works only with latest stable (no more than 6 weeks old).

**Comment by jeroen** [comment]
Unfortunately on Linux the version of cargo is beyond my control. We need to build using the version of cargo from the apt/rpm repositories: https://packages.ubuntu.com/trusty-updates/cargo

**Comment by kornelski** [comment]
Oh, that's going to be tough. Can you ignore the packages and use rustup.sh?

**Comment by jeroen** [comment]
No I'm not allowed to install custom software on the build server. But I can just pin lodepng to an old version that works in my `Cargo.lock` file.

**Comment by kornelski** [comment]
OK, if you can do that, that's great.

**Comment by kornelski** [comment]
Were you able to fix the invalid_state problem using the latest release or code on master?

**Comment by jeroen** [comment]
Yes I am no longer seeing this warning. I'm not sure if it's due to the new version of gifski, or something else in the stack that I updated.

**Comment by jeroen** [comment]
Thanks again!
