### ISSUE TITLE
Problem with new GIF/LZW optimizer

### ISSUE THREAD

**Issue by AiZ** [ImageOptim/gifski#54]
Hello,

There's (again) a new optimizer for GIF files.
[https://encode.ru/threads/3008-flexiGIF-lossless-GIF-LZW-optimization](https://encode.ru/threads/3008-flexiGIF-lossless-GIF-LZW-optimizationl)
[https://create.stephan-brumme.com/flexigif-lossless-gif-lzw-optimization/](https://create.stephan-brumme.com/flexigif-lossless-gif-lzw-optimization/)
GIF files generated with gifski v0.8.5 are problematic with this tool while v0.8.2 and below encodes are OK (took 10 png frames from [Big Buck Bunny](https://media.xiph.org/BBB/BBB-360-png/) for the test).
Would you mind participate to the discussion on encode.ru forum?

Thanks in advance,

    AiZ

**Comment by stbrumme** [comment]
As you know, LZW data is split in blocks with at most 255 bytes.
Unused bits of the last byte of a frame have to be filled with dummy data. However, there are 8 unused bits in the 7th frame, so the entire last byte is redundant. (gifski 0.8.5)
![bigbunny_frames_1_to_10](https://user-images.githubusercontent.com/14121853/45616952-259e4400-ba71-11e8-8eb2-051721aa74ad.gif)

**Comment by kornelski** [comment]
gifski encodes GIFs using Piston's encoder, so LZW bugs are best filled there: https://github.com/PistonDevelopers/image

**Comment by stbrumme** [comment]
I added a workaround in my code for that situation (display an error message, skip the unused/redundant byte and continue).
FYI: I never saw 9 or more unused bits, so it seems to be a typical off-by-one issue.
