### ISSUE TITLE
GifskiError to string API

### ISSUE THREAD

**Issue by jeroen** [ImageOptim/gifski#55]
It would be useful to expose a function that translates the `GifskiError` enum into an error message string that the application or can show to the user. Similar to e.g. [curl_easy_strerror](https://curl.haxx.se/libcurl/c/curl_easy_strerror.html).

**Comment by sindresorhus** [comment]
Would be nice. I currently [have all the error messages hardcoded](https://github.com/sindresorhus/gifski-app/blob/f851b6f385f97d98130469bf7b1aacaf68bb16c6/Gifski/GifskiWrapper.swift#L20-L47).
