### ISSUE TITLE
Segfault on i686-pc-windows-gnu since v0.8.4

### ISSUE THREAD

**Issue by jeroen** [ImageOptim/gifski#56]
After upgrading from 0.8.3 (which worked fine) to 0.8.6 my bindings start segfaulting during the examples on mingw32 (`i686-pc-windows-gnu`). The problem does not occur on Linux or MacOS or even `x86_64-pc-windows-gnu`, only on 32bit windows. 

It looks like the problem started somewhere in between 0.8.3 and 0.8.4. I'm sorry for not being able to provide more detailed information, I'm having a hard time getting a backtrace from gdb on Windows. Below what I am seeing.

Any guess to something that could have changed after 0.8.3 that affects i386 targets? There may also be a conflict between the version of gcc mingw32 that I use to compile my bindings and the one rust assumes, though it was working fine before.

<img width="426" alt="capture" src="https://user-images.githubusercontent.com/216319/46177711-355d2a00-c2b4-11e8-907b-74bc8f23ead2.PNG">

**Comment by kornelski** [comment]
I don't know much about win-gnu, unfortunately.

**Comment by jeroen** [comment]
OK well the problem was fixed for me by upgrading gcc.
