### ISSUE TITLE
failed to run custom build command for `ffmpeg-sys v4.0.2

### ISSUE THREAD

**Issue by euppi98** [ImageOptim/gifski#59]
I try to compile the command - "cargo build --release --features=video" and give this error:
> failed to run custom build command for `ffmpeg-sys v4.0.2 (https://github.com/meh/rust-ffmpeg-sys#55323cb9)

![screen shot 2018-10-17 at 01 26 40](https://user-images.githubusercontent.com/23306157/47051309-6f7f6480-d1ac-11e8-8171-1bb0b6fe4bdd.png)

**Comment by euppi98** [comment]
I installed ffmpeg 3, the same error!!!

**Comment by kornelski** [comment]
As the message says, it can't find `libavutil`

```sh
pkg-config --libs --cflags libavutil
```

must work, and it must be libavutil that is ffmpeg-3-compatible. Perhaps ffmpeg@3 package has renamed all the libraries, so they're libavutil@3 or such. Alternatively their `.pc` files are in ffmpeg3 directory, and not in the system-global pkg-config directory, so pkg-config doesn't know about them.

**Comment by accelsao** [comment]
> As the message says, it can't find `libavutil`
> 
> ```shell
> pkg-config --libs --cflags libavutil
> ```
> 
> must work, and it must be libavutil that is ffmpeg-3-compatible. Perhaps ffmpeg@3 package has renamed all the libraries, so they're libavutil@3 or such. Alternatively their `.pc` files are in ffmpeg3 directory, and not in the system-global pkg-config directory, so pkg-config doesn't know about them.

how to run with command: `pkg-config --libs --cflags libavutil` in win10?

**Comment by kornelski** [comment]
Oh, it's going to be a nightmare to try to get ffmpeg working on Windows. I can't help you with that.
