### ISSUE TITLE
Strange output when using WebM video directly

### ISSUE THREAD

**Issue by phw** [ImageOptim/gifski#6]
I tried to convert the WebM video file in [test.zip](https://github.com/ImageOptim/gifski/files/1444074/test.zip) directly with:

    gifski -o a.gif test.webm

The result is this:

![a](https://user-images.githubusercontent.com/29852/32415255-ff51aa22-c236-11e7-9e89-06c4fa09c554.gif)

When I first convert the video to frames with ffmpeg and convert the frames I get a proper result:

    ffmpeg -i test.webm frame%04d.png
    gifski -o b.gif frame*.png

![b](https://user-images.githubusercontent.com/29852/32415265-2d8e4c56-c237-11e7-8bee-3a91427a4d4f.gif)

Tested with latest master revision and ffmpeg 3.4.

**Comment by pornel** [comment]
Yeah, video decoding is very rough at the moment.

**Comment by pornel** [comment]
This bug is fixed in master.

BTW: video files most often have chroma subsampling, which is toxic for GIFs. I recommend encoding in "444" mode or using `--width` option to resize videos to 50% of their size.
