### ISSUE TITLE
Can't Open Gif

### ISSUE THREAD

**Issue by GKid94** [ImageOptim/gifski#65]
I have an issue with the Gifski Gif’s I can’t open them on my Android phone but when I use other encoders the Gif’s work

**Comment by kornelski** [comment]
What do you use on Android to open it?

Can you share the problematic animation?

**Comment by GKid94** [comment]
I use the system Gallery app and it shows a black image and it says "Can't load the thumbnail"

**Comment by kornelski** [comment]
I don't know what to do about this. GIFs generally work for me.
