### ISSUE TITLE
This doesn't work with JPG/JPEG files does it....?

### ISSUE THREAD

**Issue by DumbJoe** [ImageOptim/gifski#66]
Or do you need to convert them to png before I can use this? Because I get: https://i.imgur.com/XuIE6Gf.png

**Comment by kornelski** [comment]
Yeah, PNG only.

**Comment by DumbJoe** [comment]
Oh.....can you make it also work with jpeg/jpg files too and all other image formats too(like tiff, tga, etc.,)?

**Comment by kornelski** [comment]
There is no loss of quality in conversion to PNG.

**Comment by DumbJoe** [comment]
AH-huh....

Well there isn't a replacement image format that supports animation on all browsers, is there? Supposedly APNG is one but not one seems to be interested in that or if there is, I haven't seen any sites use APNG and are of mainly GIF formats....there was a couple of others too if I recall but I don't remember their names and they have been forgotten as well.....

**Comment by kornelski** [comment]
H.264 in MP4 container plays in most browsers, and is 10&times; more efficient than GIF (even more so at higher resolutions). APNG and AWebP are awful primitive formats, as inefficient as GIF — don't bother with them.

There is a [fake distinction](https://kornel.ski/efficient-gifs) between animating in `<img>` tag, and `<video muted playsinline autoplay>` tag. At least [Safari is fixing this](https://calendar.perfplanet.com/2017/animated-gif-without-the-gif/).

**Comment by DumbJoe** [comment]
Heh, apparently Firefox doesn't even support AWebP format, but plays APNGs fine.....which is at least better than GIF when it comes to quality wise but you're right about file size which must be small if you're hosting a website or content....but for sharing on like forums or posts and the likes, I guess APNG is alright...?

Okay, and what of various discussion forums/comment sections that don't support silent MP4 files as image files for the purpose of submitting an inline image as an animation?

Because some of them you can't just code in the html code to hack this in as html code would be disabled and must resort to bbcode or something similar....

And what about about popular image sharing websites like Imgur and PostImage, do they support uploading and sharing silent MP4s as animated image files?

I'm also guessing that's why you have no interest in developing a feature to turn jpg/jepgs and other image formats straight without converting to png first? And if you're using PNGs as the basse image format, may as well turn them into APNGs instead of GIFs to preserve quality! hahahaha

**Comment by kornelski** [comment]
I'm well aware that most sites/forums don't support MP4 uploads, which is why gifski exists :)

I don't see any use for APNG nor AWebP in any circumstance.

**Comment by DumbJoe** [comment]
> I'm well aware that most sites/forums don't support MP4 uploads, which is why gifski exists :)

...and you wonder why GIF is still alive..... :P I thought you were trying to kill it, not keep it alive! hahaha Make up your mind!

>JPEG as an intermediate step should be avoided as it lowers quality and adds distortions that are problematic for GIF.

And what if they were the original picture format or the only source is JPG/JPEG format that the author has uploaded? For example you google some pictures of a relevant subject and want to turn them in a short animation, and they are only saved as jpg/jpeg and not bitmap/png/other lossless/uncompressed format?

>There's no upside to them compared to either GIF (well supported) or MP4/WebM (well compressed). APNG and AWebP are both poorly compressed and poorly supported.

Dunno about AWebP, but APNG is supposed to have better clarity if compared to a GIF of the same settings(Even if it was made using your program, gifski which only really fixes the colour banding issue...), thanks to its lossless compression algorithm, or have you forgotten that PNGs are a lossless and not lossy format?

Sure H.264 through MP4 (dunno about WebM though...) can also be lossless if you have the Rate Factor setting at 0 when encoding which according to handbrake is lossless and have the same clarity as the original video though it would kinda be a waste of space if the source original was in a lossy format or and compression...

Also as a side note before I forget, I appear to be unable to increase the frame rate from the default 20. I have tried this command but the animation still looks laggy... Oh and is there a way to alter the speed as well? Like speed up or slow down to accommodate the increase in frame rate as increasing frame rate also speeds up the animation......when I just want to have smoother playback but not as fast playback speed....

`gifski --fps 80 --quality 100 -o anim80fps.gif C:\Users\Riolu\Downloads\69276932_ugoira600x600\69276932_ugoira1920x1080\*.png`

**Comment by DumbJoe** [comment]
I also tried `gifski --fps 80 --quality 100 C:\Users\Riolu\Downloads\69276932_ugoira600x600\69276932_ugoira1920x1080\*.png -o anim80fps.gif ` s that is the correct command format but that still doesn't encode the GIF file with a frame rate of 80 instead of the default 20.....

**Comment by DumbJoe** [comment]
*as 

PS - can't edit my posts since I'm using an older Firefox 52.9 ESR build.... 

...........................................________........................ 
....................................,.-‘”...................``~.,.................. 
.............................,.-”...................................“-.,............ 
.........................,/...............................................”:,........ 
.....................,?......................................................\,..... 
.................../...........................................................,}.... 
................./......................................................,:`^`..}.... 
.............../...................................................,:”........./..... 
..............?.....__.........................................:`.........../..... 
............./__.(.....“~-,_..............................,:`........../........ 
.........../(_....”~,_........“~,_....................,:`........_/........... 
..........{.._$;_......”=,_.......“-,_.......,.-~-,},.~”;/....}........... 
...........((.....*~_.......”=-._......“;,,./`..../”............../............ 
...,,,___.\`~,......“~.,....................`.....}............../............. 
............(....`=-,,.......`........................(......;_,,-”............... 
............/.`~,......`-...............................\....../\................... 
.............\`~.*-,.....................................|,./.....\,__........... 
,,_..........}.>-._\...................................|..............`=~-,.... 
.....`=~-,_\_......`\,.................................\........................ 
...................`=~-,,.\,...............................\....................... 
................................`:,,...........................`\..............__.. 
.....................................`=-,...................,%`>--==``....... 
........................................_\..........._,-%.......`\............... 
...................................,<`.._|_,-&``................`\..............

**Comment by DumbJoe** [comment]
Oh that turned out bad....how about just an emote instead: 🤦

**Comment by kornelski** [comment]
For GIF 20fps (delay=5) is the max safe framerate. Sometimes delay=3 works (33fps), but everything higher won't work. 
That's because Netscape-era GIFs had all kinds of garbage framerates of 50fps, 100fps, etc., but the browsers were so slow that they didn't actually animate at that speed. 
Once browsers got faster, old GIFs with ridiculous framerates started looking stupid, so browsers had to start ignoring high framerates for backwards compatibility. So when GIF sets framerate to "too fast", based on browsers heuristics, it can actually mean slow framerate. 

Also note that GIF supports only 100/n framerates, while most displays only 60/x, so 20fps is the maximum framerate that can be displayed smoothly. Everything else, even if it worked, would be jerky and frameskip.

That's the GIF. A fractal of garbage.


APNG supports either:

* 24/32-bit, which is 3-4 fatter than GIF. Ridiculous, you wouldn't want to touch it for anything larger than an animated emoji.
* or 1 palette for the entire file. That gives reasonable compression, but limited quality.

GIF supports adding one new palette *per frame*, which GIFski uses to achieve thousands of colors at file sizes smaller than fully lossless true color.

So APNG is either worse compressed than GIF, or worse looking than GIF. Either way it's bad.

**Comment by DumbJoe** [comment]
> For GIF 20fps (delay=5) is the max safe framerate. Sometimes delay=3 works (33fps), but everything higher won't work. That's because Netscape-era GIFs had all kinds of garbage framerates of 50fps, 100fps, etc., but the browsers were so slow that they didn't actually animate at that speed. Once browsers got faster, old GIFs with ridiculous framerates started looking stupid, so browsers had to start ignoring high framerates for backwards compatibility. So when GIF sets framerate to "too fast", based on browsers heuristics, it can actually mean slow framerate.

I see, well it just so happens APNG doesn't have this problem.....unless it does but for some reason views as intended on my end?

Also isn't delay=5, 200fps and delay=3 is 333.3 recurring fps? Because there is 1000 milliseconds in a second.....unless you're using another method of measurement?

[According to this comment(I can't actually link the comment because the post so so old that there probably wasn't a comment link or that the forum upgraded so much that it broke old comment styles or something...), it was because of performance reasons, not backwards compatibility](http://forums.mozillazine.org/viewtopic.php?f=38&t=36512)

Oh, according to [this](https://blogs.msdn.microsoft.com/ieinternals/2010/06/07/trivia-animated-gif-timing/) it's actually 10fps on IE browsers because of "compatibility reasons"...............hmmmmmmmmmmmmmmmmmm..............

> Also note that GIF supports only 100/n framerates, while most displays only 60/x, so 20fps is the maximum framerate that can be displayed smoothly. Everything else, even if it worked, would be jerky and frameskip.

Well it just so happens I have a monitor that can output 144Hz.....so it should definitely look smoother than 20fps....but thanks to this hard coded limit.......

>GIF supports adding one new palette per frame, which gifski uses to achieve thousands of colors at file sizes smaller than fully lossless true color.

So the higher the frame rate, the more colours it uses? OR is the frame divided evenly and split further where gifski stitches those frames up together to become one whole and then GIF's it with other frames using the same process? 

But according to you, can only reach up to 3k colours, where as true colour is 16,777,216 units, far more than the 3000 figure.....I don't understand how 3000 colours appears to be superior to 16,777,216 colours of APNG? Plus you get the extra Alpha channel for transparency or other cool effects....which a GIF can't do...

But of course the downside of having more colours per pallette is increased file size....

**Comment by DumbJoe** [comment]
OK so found out 50 fps is the max it will go before negative affects come in to play, mainly micro-stutter for me for some reason, and eventually if you go high enough, the micro-stutter(?) or the browser used to view the gif will drop the fps down to 10 or less.... I've done a test on one encoded for exactly 10 fps and even the encoded 10fps looks smoother than a 100fps gif that lagged so much it looks like 10fps or less....or a limitation like you said earlier kicking in.....where browsers would just cap just then reset the fps to 10.....

**Comment by DumbJoe** [comment]
> If JPEGs are your input, WebM/H.264 will deal with them very well, even at nearly-lossless quality levels. They all use similar color space and block-based compression, so JEPG distortions are friendly to them.

Yes.....except they don't loop, where as with a APNG or GIF, they looop automatically... Yes, some players will have an option loop, but for my particular place, it doesn't....(and there doesn't appear to be an option either...I have a weird getup, I know...)which is why I asked about it in the first place... Also they're classified as video files and not image files so if I were to sort them by type, they'd be way down there after all my other image files....

> I have no plans for adding support of JPEG as an input. 

Why do you have no plans adding support for JPEG? Is it because you assume FFMPEG is available to use instead to convert to png frames? What if I don't want that extra bloat and only need this small program and happen to only have other than png files to work with and only just wanna make an animated gif file? Wouldn't it be more convenient to accept other file types rather needing to first convert them all to png as an intermeditary step because gifski doesnt support anything other than png files?

**Comment by kornelski** [comment]
> Why do you have no plans adding support for JPEG?

To make it harder to make a mistake. Some people don't care about differences between image formats, and would assume that JPEG input is as good as PNG input. But it's not. JPEG artifacts, even when they're invisible to the naked eye, add a bloat to paletted GIF, and make files larger and look worse.

It's a non-obvious gotcha, so I intentionally make the worse choice more annoying.

**Comment by DumbJoe** [comment]
But converting from jpg to png just to get the program to work would defeat the purpose of your principle....since now the png will carry over the same jpg compression artifacts of the original image if there was any to start with.

> would assume that JPEG input is as good as PNG input

If the source came from a jpg format, then yes, it would be as good as the png input if it was converted from jpg source prior....the only difference is increased file size, pointlessly, and turning the image from lossy to lossless - also pointless as you can simply save the new changes if any, as a new file...unless you intend on using the image with something else and keep it that all whilst still wanting to retain its original clarity on the same file....

**Comment by kornelski** [comment]
You're not supposed to convert from JPEG to PNG. You're supposed to export your original source straight to PNG instead of JPEG.

This inconvenience is the point. I'm doing this exactly to make use of JPEG annoying. It's exactly to add you this extra pointless wasteful work, so that you'll pause and think "wait, JPEG to PNG conversion is dumb, why am I doing this!?"

**Comment by DumbJoe** [comment]
Ok, so what do I do when I come across original source being JPEG from a google search and want to turn into an gif animation except the author didn't provide a png alternative file format? Am I gonna somehow contact the author whose not left any contact details or method at all of a way to contact them and ask them to give me a png export version just so I can use your gifski on?
