### ISSUE TITLE
Unable to install gifski on ubuntu 18.04

### ISSUE THREAD

**Issue by arthurlutz** [ImageOptim/gifski#71]
I get the following with rustc and cargo installed from packages : 

```
$ cargo install gifsk
[snip]
   Compiling gifski v0.8.7                                                                         
error: Edition 2018 is unstable and only available for nightly builds of rustc.                    
                                                                                                   
error: failed to compile `gifski v0.8.7`, intermediate artifacts can be found at `/tmp/cargo-installDtI402`

Caused by:
  Could not compile `gifski`.

To learn more, run the command again with --verbose.
$ rustc --version
rustc 1.30.0
$ cargo --version
cargo 1.30.0
```

With verbose I get https://paste.debian.net/1065735/ (doesn't seem to be more information there)

Sorry am a noobie as far as rust is concerned.

**Comment by arthurlutz** [comment]
ok, seing 0.8.5 was the lastest stable release, I tried `cargo install gifski --version 0.8.5` which works !

**Comment by kornelski** [comment]
The version on master requires Rust 1.31.

1. If something doesn't compile, run `rustup update`. 99% of the time it's only because your compiler is out of date.

2. Debian's compiler is always out of date. Use Rust from `rustup`.
