### ISSUE TITLE
Quality 0 shows only first frame

### ISSUE THREAD

**Issue by phw** [ImageOptim/gifski#8]
Not sure if this is intentional, but with quality set to 0 only the first frame is filled. All other frames are completely transparent:

![quality0](https://user-images.githubusercontent.com/29852/32415506-1166360c-c23b-11e7-8714-c8f389bae42e.gif)

Quality 1 will show the animation again:

![quality01](https://user-images.githubusercontent.com/29852/32415512-1e01efc8-c23b-11e7-8742-1de6648e2972.gif)

**Comment by pornel** [comment]
It's a logial consequence. If you accept unlimited distortion then any frame is good enough, so it may as well be transparent.

**Comment by pornel** [comment]
I recommend not allowing users to set quality below 20. With quality too low all frames will look bad, and file size will be wasted on poorly correcting poorly rendered frames.
