### ISSUE TITLE
First frame was blank while created GIF using gifski binary in AWS lambda function.

### ISSUE THREAD

**Issue by Hemant11111** [ImageOptim/gifski#80]
**The images used to create gif**:

![o6](https://user-images.githubusercontent.com/15008930/56889425-f2ef0c00-6a93-11e9-805d-f54034718343.png)
![o5](https://user-images.githubusercontent.com/15008930/56889427-f2ef0c00-6a93-11e9-8e18-f297d92bc0fa.png)
![o4](https://user-images.githubusercontent.com/15008930/56889428-f387a280-6a93-11e9-9c7c-5efc78bd0f4a.png)
![o3](https://user-images.githubusercontent.com/15008930/56889429-f387a280-6a93-11e9-943e-487b473d7576.png)
![o2](https://user-images.githubusercontent.com/15008930/56889430-f4203900-6a93-11e9-8bed-31ad7de457a8.png)
![o1](https://user-images.githubusercontent.com/15008930/56889433-f4203900-6a93-11e9-9e74-84111ecae1be.png)

**command used:**
`gifski -o 5a096a.gif o1.png o1.png o1.png o2.png o2.png o2.png o3.png o3.png o3.png o4.png o4.png o4.png o5.png o5.png o5.png o6.png o6.png o6.png --fps 2 -W 500 -H 400`

**Output**:
![5a096a](https://user-images.githubusercontent.com/15008930/56889457-ff736480-6a93-11e9-8c1f-0f80e9cf3db3.gif)
All images were in png format. Tested multiple times. First frame was always blank. **-W 500 -H 400**  resizing height and width were not working as well neither on local nor on AWS lambda function. Same first frame distortion issue was generated with command having **fps 1**
`gifski -o 5a096a.gif o1.png o1.png o1.png o2.png o2.png o2.png o3.png o3.png o3.png o4.png o4.png o4.png o5.png o5.png o5.png o6.png o6.png o6.png --fps 1 -W 500 -H 400`

This is output of command at local. _Command is working fine on local._
![local](https://user-images.githubusercontent.com/15008930/56891432-056c4400-6a9a-11e9-965f-b7eb1041c26c.gif)

**Comment by kornelski** [comment]
Try 0.10.1, it fixes an issue with frame ordering.
