### ISSUE TITLE
The estimated size is a little bit off 

### ISSUE THREAD

**Issue by JuanitoFatas** [ImageOptim/gifski#84]
Hello!

Thank you for this great Mac app. Love it! 😍 

I noticed the estimated file size is off by a magnitude of 10.

Estimated:

<img width="821" alt="Screenshot 2019-05-23 23 15 27" src="https://user-images.githubusercontent.com/1000669/58260640-cb990f80-7db1-11e9-8808-2db18bc80ec2.png">

Result size:

<img width="818" alt="Screenshot 2019-05-23 23 21 38" src="https://user-images.githubusercontent.com/1000669/58260641-cb990f80-7db1-11e9-9d95-89b49307d7cd.png">

Browsing through the codebase, cannot find a place to fix it. Is this a bug from mac Finder?

I am on macOS 10.14.4 and Gifski 1.8.0 (17).

Thanks in advance!

**Comment by kornelski** [comment]
The estimate assumes there's a lot of movement in the video. It's hard to know that without processing the video first: #28

**Comment by JuanitoFatas** [comment]
Ah I see! It is pretty accurate if we divide the current estimated size by 10 😅 
Thanks anyway!
