### ISSUE TITLE
Instruction For Noobs?

### ISSUE THREAD

**Issue by GeorgeDziov** [ImageOptim/gifski#86]
Well, title is quite self explanatory so step-by-step guide wouldn't hurt to be honest.
Windows user.

**Comment by bekicot** [comment]
Noobs in which context?
Maybe starts by telling which parts of the readme that you don't understand.

In my opinion, this project assumes familiarities with command line.

**Comment by GeorgeDziov** [comment]
"assumes familiarities with command line" - that's the point, I'm not familiar with cmd well enough, I even play dos games via dosbox drag'n'drop instead of typing the path.

I understand when a programmer tells people they should learn one thing or another and that's right but today including a nice detailed [tutorial/example] for beginners is a good practice in general (many people do that), it lets them learn and experiment, especially when there's no way to find [one] in the internet.

Of course it's your product and you decide how to package/advertise it, my post here is just a request, nothing more.

**Comment by kornelski** [comment]
Sorry, I have GUI only for macOS. I can't provide you a Windows GUI.

It's not my place to explain how command line works. You can learn that from any other site.

**Comment by GeorgeDziov** [comment]
kornelski so it's your invention then?

Of course I can, thanks for noting but I wasn't talking about how cmd works itself, I asked about a tutorial how to work with the combination of this tool and cmd, you need to explain cmd at least partially since you promote use of cmd.

Sure I'll wait for someone to make one but I wonder why can't you do that? I understand if you don't want to explain though, I'm ok with that.

**Comment by GeorgeDziov** [comment]
Ok I see the [ISSUE] is least likely to be resolved so I'm closing it.

Thanks for attention and good day.

**Comment by DumbJoe** [comment]
> In my opinion, this project assumes familiarities with command line.

By that logic, then anyone who runs a computer is to be assumed they know how to fix their own problems if anything happens or having a car for you to already know how to fix your own car if it breaks down.
