### ISSUE TITLE
Options to specify directory, instead of list of frames

### ISSUE THREAD

**Issue by bekicot** [ImageOptim/gifski#87]
allow

```sh
$ gifski images/ --output=movies.gif
```

## Why?

I use gifski to generate simulation. I have 18000 plots to be converted into 15 minutes gif (20 fps). Passing 18000 images as argument (512 kb buffer) is not currently viable on Mac osx.

**Comment by kornelski** [comment]
It could be doable, but are you prepared to deal with a GIF made from 18K frames? It may be hundreds of MB large file.

**Comment by bekicot** [comment]
> It could be doable, but are you prepared to deal with a GIF made from 18K frames? It may be hundreds of MB large file.

It will be 30 megs, I have implemented it :). Will make a pull request soon.
I understand, and now I'm considering using mp4 or WebM instead.
