### ISSUE TITLE
Problem with Mac app in Catalina

### ISSUE THREAD

**Issue by ivanvorobei** [ImageOptim/gifski#88]
I am use `Catalina Beta 2`. See record:

![ScreenRecording2019-06-24at2](https://user-images.githubusercontent.com/10995774/60049870-f1c70d80-96d7-11e9-98de-d1341f0d1ae9.gif)

In `Mojave` all work correctly.

**Comment by sunshinejr** [comment]
@ivanvorobei hey yeah I also have the same problem, beta 1 was alright. I submitted a feedback (FB6240463) so let's hope for a fix in a future betas.

**Comment by sindresorhus** [comment]
This was fixed in Catalina beta 5: https://github.com/sindresorhus/Gifski/issues/99
