### ISSUE TITLE
First time user - getting segfaults all the time

### ISSUE THREAD

**Issue by seefood** [ImageOptim/gifski#9]
Till today I was a happy user of [gifify from bash-it](https://github.com/Bash-it/bash-it/blob/master/plugins/available/gif.plugin.bash). today I found gifski and immediately wanted to compare speed and quality. Problem is I keep getting segfaults. Using the precompiled binary deb on Ubuntu 17.10.

What debug dumps can I offer you?

**Comment by pornel** [comment]
Try if it works if you compile it on your machine.
```sh
curl https://sh.rustup.rs -sSf | sh
git clone https://github.com/ImageOptim/gifski.git
cd gifski
cargo run --release -- # your args here
```

**Comment by seefood** [comment]
I'll start with apt-getting rustc, if its all the same, I like being able to easily clean up after (small laptop disk...)

**Comment by seefood** [comment]
didn't get very far...
```
   Compiling color_quant v1.0.0
   Compiling vec_map v0.8.0
   Compiling ffmpeg v0.2.0-alpha.2 (https://github.com/pornel/rust-ffmpeg.git#0eea6d01)
   Compiling void v1.0.2
   Compiling peeking_take_while v0.1.2
   Compiling bitflags v0.9.1
   Compiling imgref v1.3.0
   Compiling libc v0.2.33
error[E0599]: no method named `min` found for type `usize` in the current scope
  --> /home/ira/.cargo/registry/src/github.com-1ecc6299db9ec823/imgref-1.3.0/src/iter.rs:75:56
   |
75 |             self.buf_left = &self.buf_left[self.stride.min(self.buf_left.len()-1)..];
   |                                                        ^^^
   |
   = note: the method `min` exists but the following trait bounds were not satisfied:
           `usize : std::iter::Iterator`

error: aborting due to previous error(s)

error: Could not compile `imgref`.
Build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by seefood** [comment]
well, building without the video extensions works. do you wish to debug this further?

**Comment by seefood** [comment]
to elaborate: it finishes building and runs without segfaults, but not when requesting video extensions:
```
[...]
   Compiling ffmpeg-sys v3.4.0 (https://github.com/meh/rust-ffmpeg-sys#8a6d9c6e)
error: failed to run custom build command for `ffmpeg-sys v3.4.0 (https://github.com/meh/rust-ffmpeg-sys#8a6d9c6e)`
process didn't exit successfully: `/home/ira/src/gifski/target/release/build/ffmpeg-sys-ffb494eb226244e4/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libavformat\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package libavformat was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libavformat.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libavformat\' found\n" } }', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by pornel** [comment]
Yeah, video is expected to be PITA to compile. I will be switching too gstreamer, which is easier to redistribute.

So another source of crashes could be OpenMP integration, try:

cargo run --release --features=openmp


BTW, is your CPU reasonably new? (<10 years old?)

**Comment by seefood** [comment]
The openMP is just fine. Only the video gives me problems. I'll just use the compiled version instead of the deb.

I'm rolling this into a function and pushing it to bash-it as well, It will be a nice addition to my too-large GIF collection (which I'd love to convert to webm once twitter, whatsapp and everyone supports it)

**Comment by seefood** [comment]
...And the CPU is quite modern, `Xeon Gold 5115 CPU @ 2.40GHz`

**Comment by DNA** [comment]
Just for future reference, here's the list of packages I needed to install to compile successfuly with ffmpeg and openmp on ubuntu:

`sudo apt-get install libavformat-dev libavfilter-dev libavdevice-dev libclang-dev clang`

**Comment by seefood** [comment]
Thanks! Compiled nicely and with only one warning, nice!
@pornel, I'd appreciate if those dependencies get mentioned in the README. Thanks!
